package releases

import (
	"context"
	"fmt"
	"strings"
)

// defaultMiseJavaEndpoint is Mise's Java release metadata mirror for GA Linux
// x86_64 JDKs. The version set is platform-independent, so a single platform is
// queried to enumerate versions.
//
// This is the same source mise's core Java plugin uses (URL form
// https://mise-java.jdx.dev/jvm/{release_type}/{os}/{arch}.json):
// https://github.com/jdx/mise/blob/main/src/plugins/core/java.rs
// The metadata is generated by the jdx/mise-java crawler:
// https://github.com/jdx/mise-java
const defaultMiseJavaEndpoint = "https://mise-java.jdx.dev/jvm/ga/linux/x86_64.json"

// MiseJavaClient lists JDK releases for one vendor from Mise's Java metadata
// mirror. It covers Java vendors other than Temurin (see [TemurinClient], which
// uses the Adoptium API directly): zulu, corretto, liberica, oracle, etc.
type MiseJavaClient struct {
	base
	vendor string
}

var _ Lister = (*MiseJavaClient)(nil)

// NewMiseJavaClient returns a Java release metadata client for vendor.
func NewMiseJavaClient(vendor string, opts ...Option) *MiseJavaClient {
	return &MiseJavaClient{base: newBase(defaultMiseJavaEndpoint, opts...), vendor: strings.TrimSpace(vendor)}
}

// List returns JDK releases for the configured Java vendor.
func (c *MiseJavaClient) List(ctx context.Context) ([]Release, error) {
	if c.vendor == "" {
		return nil, fmt.Errorf("mise java: vendor is required")
	}
	type item struct {
		Vendor    string `json:"vendor"`
		Version   string `json:"version"`
		ImageType string `json:"image_type"`
	}
	return fetch(ctx, c.base, func(items []item) []Release {
		releases := make([]Release, 0, len(items))
		for _, it := range items {
			if !strings.EqualFold(strings.TrimSpace(it.Vendor), c.vendor) ||
				!strings.EqualFold(strings.TrimSpace(it.ImageType), "jdk") {
				continue
			}
			version := strings.TrimSpace(it.Version)
			releases = append(releases, Release{
				Version: version,
				Stable:  version != "" && !isPrerelease(version),
			})
		}
		return releases
	})
}
