package graph

import (
	"context"
	"testing"
)

func TestPubResolver_Ecosystem(t *testing.T) {
	r := NewPubResolver()
	if got := r.Ecosystem(); got != "Pub" {
		t.Errorf("Ecosystem() = %q, want %q", got, "Pub")
	}
}

func TestPubResolver_ResolveEdges_PubspecLock(t *testing.T) {
	pubspecLock := `# Generated by pub
# See https://dart.dev/tools/pub/glossary#lockfile
packages:
  args:
    dependency: transitive
    description:
      name: args
      sha256: "7cf60b9f0cc88203c5a190b4cd62a99feea42759a7fa695010eb5de1c0b2252a"
      url: "https://pub.dev"
    source: hosted
    version: "2.4.2"
  async:
    dependency: transitive
    description:
      name: async
      sha256: "947bfcf187f74dbc5e146c9eb9c0f10c9f8b30743e341481c1e2ed3ecc18c20c"
      url: "https://pub.dev"
    source: hosted
    version: "2.11.0"
  collection:
    dependency: "direct main"
    description:
      name: collection
      sha256: "a1ace0a119f20aabc852d165077c036cd864571f394880e86c8c479ad73b8e26"
      url: "https://pub.dev"
    source: hosted
    version: "1.19.0"
  flutter:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
  flutter_test:
    dependency: "direct dev"
    description: flutter
    source: sdk
    version: "0.0.0"
  http:
    dependency: "direct main"
    description:
      name: http
      sha256: "761a297c042deedc1ffbb156d6e2af13886bb305c2a343a4d972504cd67dd938"
      url: "https://pub.dev"
    source: hosted
    version: "1.1.2"
  json_annotation:
    dependency: transitive
    description:
      name: json_annotation
      sha256: "1ce844379ca14835a50d2f019a3099f419082cfdd231cd86a142af94dd5c6bb1"
      url: "https://pub.dev"
    source: hosted
    version: "4.8.1"
sdks:
  dart: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"
`

	files := &mockFileReader{
		files: map[string][]byte{
			"pubspec.lock": []byte(pubspecLock),
		},
	}

	g := New()
	r := NewPubResolver()

	err := r.ResolveEdges(context.Background(), g, files)
	if err != nil {
		t.Fatalf("ResolveEdges() error = %v", err)
	}

	// Should have 7 packages
	nodeCount := 0
	for range g.Nodes() {
		nodeCount++
	}
	if nodeCount != 7 {
		t.Errorf("Expected 7 nodes, got %d", nodeCount)
	}

	// Check direct dependency
	collectionPURL := "pkg:pub/collection@1.19.0"
	if node := g.Node(collectionPURL); node == nil {
		t.Errorf("Expected node %s to exist", collectionPURL)
	} else if !node.Direct {
		t.Errorf("Expected %s to be marked as direct", collectionPURL)
	}

	// Check another direct dependency
	httpPURL := "pkg:pub/http@1.1.2"
	if node := g.Node(httpPURL); node == nil {
		t.Errorf("Expected node %s to exist", httpPURL)
	} else if !node.Direct {
		t.Errorf("Expected %s to be marked as direct", httpPURL)
	}

	// Check transitive dependency
	argsPURL := "pkg:pub/args@2.4.2"
	if node := g.Node(argsPURL); node == nil {
		t.Errorf("Expected node %s to exist", argsPURL)
	} else if node.Direct {
		t.Errorf("Expected %s to be marked as transitive (not direct)", argsPURL)
	}

	// Check dev dependency - direct dev is still a direct dependency
	flutterTestPURL := "pkg:pub/flutter_test@0.0.0"
	if node := g.Node(flutterTestPURL); node == nil {
		t.Errorf("Expected node %s to exist", flutterTestPURL)
	} else if !node.Direct {
		t.Errorf("Expected %s to be marked as direct (dev)", flutterTestPURL)
	}
}

func TestPubResolver_ResolveEdges_GitDependency(t *testing.T) {
	pubspecLock := `packages:
  my_package:
    dependency: "direct main"
    description:
      path: "."
      ref: main
      resolved-ref: "abc123def456"
      url: "https://github.com/owner/my_package.git"
    source: git
    version: "1.0.0"
  another_package:
    dependency: "direct main"
    description:
      name: another_package
      sha256: "a1b2c3d4e5f6"
      url: "https://pub.dev"
    source: hosted
    version: "2.0.0"
sdks:
  dart: ">=3.0.0 <4.0.0"
`

	files := &mockFileReader{
		files: map[string][]byte{
			"pubspec.lock": []byte(pubspecLock),
		},
	}

	g := New()
	r := NewPubResolver()

	err := r.ResolveEdges(context.Background(), g, files)
	if err != nil {
		t.Fatalf("ResolveEdges() error = %v", err)
	}

	// Should have 2 packages
	nodeCount := 0
	for range g.Nodes() {
		nodeCount++
	}
	if nodeCount != 2 {
		t.Errorf("Expected 2 nodes, got %d", nodeCount)
	}

	// Git dependency
	gitPURL := "pkg:pub/my_package@1.0.0"
	if node := g.Node(gitPURL); node == nil {
		t.Errorf("Expected node %s to exist", gitPURL)
	} else if !node.Direct {
		t.Errorf("Expected %s to be marked as direct", gitPURL)
	}

	// Hosted dependency
	hostedPURL := "pkg:pub/another_package@2.0.0"
	if node := g.Node(hostedPURL); node == nil {
		t.Errorf("Expected node %s to exist", hostedPURL)
	}
}

func TestPubResolver_ResolveEdges_NoFiles(t *testing.T) {
	files := &mockFileReader{
		files: map[string][]byte{},
	}

	g := New()
	r := NewPubResolver()

	err := r.ResolveEdges(context.Background(), g, files)
	if err != nil {
		t.Fatalf("ResolveEdges() error = %v", err)
	}

	// Should have no nodes
	nodeCount := 0
	for range g.Nodes() {
		nodeCount++
	}
	if nodeCount != 0 {
		t.Errorf("Expected 0 nodes, got %d", nodeCount)
	}
}

func TestPubPkgToPURL(t *testing.T) {
	tests := []struct {
		name    string
		version string
		want    string
	}{
		{
			name:    "http",
			version: "1.1.2",
			want:    "pkg:pub/http@1.1.2",
		},
		{
			name:    "collection",
			version: "1.19.0",
			want:    "pkg:pub/collection@1.19.0",
		},
		{
			name:    "my_package",
			version: "",
			want:    "pkg:pub/my_package",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := pubPkgToPURL(tt.name, tt.version)
			if got != tt.want {
				t.Errorf("pubPkgToPURL() = %q, want %q", got, tt.want)
			}
		})
	}
}

func TestPubResolver_DependencyTypes(t *testing.T) {
	pubspecLock := `packages:
  direct_main:
    dependency: "direct main"
    description:
      name: direct_main
      url: "https://pub.dev"
    source: hosted
    version: "1.0.0"
  direct_dev:
    dependency: "direct dev"
    description:
      name: direct_dev
      url: "https://pub.dev"
    source: hosted
    version: "1.0.0"
  direct_overridden:
    dependency: "direct overridden"
    description:
      name: direct_overridden
      url: "https://pub.dev"
    source: hosted
    version: "1.0.0"
  transitive:
    dependency: transitive
    description:
      name: transitive
      url: "https://pub.dev"
    source: hosted
    version: "1.0.0"
sdks:
  dart: ">=3.0.0"
`

	files := &mockFileReader{
		files: map[string][]byte{
			"pubspec.lock": []byte(pubspecLock),
		},
	}

	g := New()
	r := NewPubResolver()

	err := r.ResolveEdges(context.Background(), g, files)
	if err != nil {
		t.Fatalf("ResolveEdges() error = %v", err)
	}

	tests := []struct {
		name       string
		wantDirect bool
	}{
		{"direct_main", true},
		{"direct_dev", true},
		{"direct_overridden", true},
		{"transitive", false},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			purl := pubPkgToPURL(tc.name, "1.0.0")
			node := g.Node(purl)
			if node == nil {
				t.Fatalf("Expected node %s to exist", purl)
			}
			if node.Direct != tc.wantDirect {
				t.Errorf("Direct = %v, want %v", node.Direct, tc.wantDirect)
			}
		})
	}
}
