'use strict';

const assert = require('node:assert/strict');
const test = require('node:test');

const { truncateMarkdown, truncationNotice } = require('./truncate-comment');

test('leaves reports within the limit unchanged', () => {
  const report = '## Deputy Dependency Diff\n\nNo dependency changes detected\n';
  assert.equal(truncateMarkdown(report, 1000), report);
});

test('truncates at a complete line and closes details before the notice', () => {
  const keptRow = `| kept | ${'x'.repeat(80)} |`;
  const droppedRow = `| dropped | ${'y'.repeat(120)} |`;
  const report = [
    '## Deputy Dependency Diff',
    '',
    '<details><summary>more findings</summary>',
    '',
    '| ID | Package |',
    '| --- | --- |',
    keptRow,
    droppedRow,
    '',
    '</details>',
    'tail',
  ].join('\n');
  const suffix = `\n\n</details>\n\n${truncationNotice}`;
  const maxBytes = Buffer.byteLength(report.slice(0, report.indexOf(droppedRow)) + suffix, 'utf8');

  const got = truncateMarkdown(report, maxBytes);

  assert.match(got, new RegExp(`${escapeRegExp(keptRow)}\\n\\n</details>\\n\\n${escapeRegExp(truncationNotice)}$`));
  assert.doesNotMatch(got, /dropped/);
  assert.ok(Buffer.byteLength(got, 'utf8') <= maxBytes);
});

test('never leaves an unpaired surrogate when truncating Unicode text', () => {
  const heading = '## Deputy Dependency Diff\n';
  const report = heading + 'a'.repeat(119 - heading.length) + '😀\nnext line';

  assert.equal(hasUnpairedSurrogate(report.slice(0, 120)), true);

  const got = truncateMarkdown(report, 120);

  assert.equal(hasUnpairedSurrogate(got), false);
  assert.ok(Buffer.byteLength(got, 'utf8') <= 120);
});

test('closes nested details blocks from the inside out', () => {
  const keptRow = `| kept | ${'x'.repeat(80)} |`;
  const droppedRow = `| dropped | ${'y'.repeat(120)} |`;
  const report = [
    '<details><summary>pre-existing findings</summary>',
    '',
    '  <details><summary>more findings</summary>',
    '',
    keptRow,
    droppedRow,
    '',
    '  </details>',
    '',
    '</details>',
  ].join('\n');
  const suffix = `\n\n  </details>\n</details>\n\n${truncationNotice}`;
  const maxBytes = Buffer.byteLength(report.slice(0, report.indexOf(droppedRow)) + suffix, 'utf8');

  const got = truncateMarkdown(report, maxBytes);

  assert.match(got, new RegExp(`${escapeRegExp(keptRow)}\\n\\n  </details>\\n</details>\\n\\n${escapeRegExp(truncationNotice)}$`));
  assert.ok(Buffer.byteLength(got, 'utf8') <= maxBytes);
});

test('keeps the complete comment below the GitHub body limit', () => {
  const report = `${'| package | version |\n'.repeat(4000)}${'😀'.repeat(4000)}`;
  const marker = '<!-- deputy:diff -->\n';
  const footer = '\n\n<sub>Generated by [Deputy](https://github.com/temporalio/deputy)</sub>';

  const body = marker + truncateMarkdown(report, 60000) + footer;

  assert.ok(Buffer.byteLength(body, 'utf8') < 65536);
  assert.match(body, new RegExp(`${escapeRegExp(truncationNotice)}${escapeRegExp(footer)}$`));
});

function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function hasUnpairedSurrogate(value) {
  for (let i = 0; i < value.length; i++) {
    const code = value.charCodeAt(i);
    if (code >= 0xd800 && code <= 0xdbff) {
      const next = value.charCodeAt(++i);
      if (!(next >= 0xdc00 && next <= 0xdfff)) {
        return true;
      }
    } else if (code >= 0xdc00 && code <= 0xdfff) {
      return true;
    }
  }
  return false;
}
