package descriptorset

import (
	"fmt"
	"strings"
	"testing"

	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protodesc"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/reflect/protoregistry"
	"google.golang.org/protobuf/types/descriptorpb"

	// Blank-import every generated deputy package so all deputy proto files
	// register in protoregistry.GlobalFiles; the drift test compares the
	// embedded descriptor set against that registry, so a package missing
	// here would exempt its protos from the check.
	_ "github.com/temporalio/deputy/gen/deputy/agent/v1"
	_ "github.com/temporalio/deputy/gen/deputy/container/v1"
	_ "github.com/temporalio/deputy/gen/deputy/dependency/v1"
	_ "github.com/temporalio/deputy/gen/deputy/diff/v1"
	_ "github.com/temporalio/deputy/gen/deputy/fix/v1"
	_ "github.com/temporalio/deputy/gen/deputy/graph/v1"
	_ "github.com/temporalio/deputy/gen/deputy/inventory/v1"
	_ "github.com/temporalio/deputy/gen/deputy/list/v1"
	_ "github.com/temporalio/deputy/gen/deputy/mcp/v1"
	_ "github.com/temporalio/deputy/gen/deputy/plugin/v1"
	_ "github.com/temporalio/deputy/gen/deputy/policy/v1"
	_ "github.com/temporalio/deputy/gen/deputy/remediation/v1"
	_ "github.com/temporalio/deputy/gen/deputy/risk/v1"
	_ "github.com/temporalio/deputy/gen/deputy/sandbox/v1"
	_ "github.com/temporalio/deputy/gen/deputy/sbom/v1"
	_ "github.com/temporalio/deputy/gen/deputy/scan/v1"
	_ "github.com/temporalio/deputy/gen/deputy/secrets/v1"
	_ "github.com/temporalio/deputy/gen/deputy/target/v1"
	_ "github.com/temporalio/deputy/gen/deputy/triage/v1"
	_ "github.com/temporalio/deputy/gen/deputy/vulnerability/v1"
)

// deputyFilePrefix identifies Deputy's own proto files in the registry and the
// embedded set; well-known and third-party imports are outside the contract.
const deputyFilePrefix = "deputy/"

// regenHint is the command that refreshes the embedded descriptor set; it
// mirrors the package doc comment.
const regenHint = "regenerate with: cd api && buf build --exclude-imports -o ../internal/proto/descriptorset/descriptorset.binpb"

// TestEmbeddedDescriptorSetMatchesGeneratedCode fails when descriptorset.binpb
// is stale: every deputy proto file linked into the binary must appear in the
// embedded set with the same messages, fields, enums, and services, and vice
// versa. The embedded set is regenerated by hand (see the package doc), so
// without this test a proto change that skips the regeneration silently drops
// the new elements' comments from MCP schemas, LSP completions, and generated
// docs. Comment-only edits do not change structure and are not caught; treat
// the regeneration as part of buf generate.
func TestEmbeddedDescriptorSetMatchesGeneratedCode(t *testing.T) {
	var fds descriptorpb.FileDescriptorSet
	if err := proto.Unmarshal(raw, &fds); err != nil {
		t.Fatalf("parse embedded descriptor set: %v", err)
	}

	embedded := make(map[string]*descriptorpb.FileDescriptorProto, len(fds.GetFile()))
	for _, fd := range fds.GetFile() {
		if !strings.HasPrefix(fd.GetName(), deputyFilePrefix) {
			continue
		}
		if fd.GetSourceCodeInfo() == nil {
			t.Errorf("embedded descriptor for %s has no source info; the set exists to carry comments (%s)", fd.GetName(), regenHint)
		}
		embedded[fd.GetName()] = fd
	}
	if len(embedded) == 0 {
		t.Fatalf("embedded descriptor set contains no %s* files", deputyFilePrefix)
	}

	linked := make(map[string]*descriptorpb.FileDescriptorProto)
	protoregistry.GlobalFiles.RangeFiles(func(fd protoreflect.FileDescriptor) bool {
		if strings.HasPrefix(fd.Path(), deputyFilePrefix) {
			linked[fd.Path()] = protodesc.ToFileDescriptorProto(fd)
		}
		return true
	})

	for path, want := range linked {
		got, ok := embedded[path]
		if !ok {
			t.Errorf("proto file %s is linked into the binary but missing from descriptorset.binpb (%s)", path, regenHint)
			continue
		}
		if diff := signatureDiff(fileSignature(want), fileSignature(got)); diff != "" {
			t.Errorf("descriptorset.binpb is stale for %s (%s):\n%s", path, regenHint, diff)
		}
	}
	for path := range embedded {
		if _, ok := linked[path]; !ok {
			t.Errorf("descriptorset.binpb contains %s, which is no longer linked into the binary; a removed proto needs a regeneration too, or a gen package import is missing from this test (%s)", path, regenHint)
		}
	}
}

// fileSignature renders the structural shape of a file descriptor (messages,
// fields, enums, services) as one line per element, so two descriptor
// representations of the same source compare equal regardless of options or
// source-info differences.
func fileSignature(fd *descriptorpb.FileDescriptorProto) []string {
	var sig []string
	pkg := fd.GetPackage()
	for _, m := range fd.GetMessageType() {
		sig = append(sig, messageSignature(pkg, m)...)
	}
	for _, e := range fd.GetEnumType() {
		sig = append(sig, enumSignature(pkg, e)...)
	}
	for _, s := range fd.GetService() {
		name := pkg + "." + s.GetName()
		sig = append(sig, "service "+name)
		for _, meth := range s.GetMethod() {
			sig = append(sig, fmt.Sprintf("rpc %s.%s(%s) %s", name, meth.GetName(), meth.GetInputType(), meth.GetOutputType()))
		}
	}
	return sig
}

// messageSignature lists a message, its fields (name, number, label, type),
// and its nested messages and enums, prefixed by the parent scope.
func messageSignature(scope string, m *descriptorpb.DescriptorProto) []string {
	name := scope + "." + m.GetName()
	sig := []string{"message " + name}
	for _, f := range m.GetField() {
		sig = append(sig, fmt.Sprintf("field %s.%s = %d %s %s %s",
			name, f.GetName(), f.GetNumber(), f.GetLabel(), f.GetType(), f.GetTypeName()))
	}
	for _, nested := range m.GetNestedType() {
		sig = append(sig, messageSignature(name, nested)...)
	}
	for _, e := range m.GetEnumType() {
		sig = append(sig, enumSignature(name, e)...)
	}
	return sig
}

// enumSignature lists an enum and its values with numbers.
func enumSignature(scope string, e *descriptorpb.EnumDescriptorProto) []string {
	name := scope + "." + e.GetName()
	sig := []string{"enum " + name}
	for _, v := range e.GetValue() {
		sig = append(sig, fmt.Sprintf("value %s.%s = %d", name, v.GetName(), v.GetNumber()))
	}
	return sig
}

// signatureDiff reports elements present in exactly one of the two signatures,
// which is enough to name what changed without a full diff engine.
func signatureDiff(want, got []string) string {
	wantSet := make(map[string]bool, len(want))
	for _, s := range want {
		wantSet[s] = true
	}
	gotSet := make(map[string]bool, len(got))
	for _, s := range got {
		gotSet[s] = true
	}
	var b strings.Builder
	for _, s := range want {
		if !gotSet[s] {
			fmt.Fprintf(&b, "  missing from embedded set: %s\n", s)
		}
	}
	for _, s := range got {
		if !wantSet[s] {
			fmt.Fprintf(&b, "  only in embedded set: %s\n", s)
		}
	}
	return b.String()
}
