package cmd

import (
	"context"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/picatz/deputy/internal/policy"
)

// evaluatePoliciesForCommand evaluates the given policies against a command and payload.
// It returns a list of actions generated by the policies, or an error if a "deny" action is encountered.
// Warnings are printed to errW (or stderr if nil), unless the command is "scan".
func evaluatePoliciesForCommand(ctx context.Context, policyPaths []string, payload map[string]any, command string, entrypoint policy.Entrypoint, errW io.Writer) ([]policy.Action, error) {
	if len(policyPaths) == 0 {
		return nil, nil
	}
	if errW == nil {
		errW = os.Stderr
	}
	if payload == nil {
		payload = map[string]any{}
	}
	env := map[string]any{
		"command": command,
	}
	if entrypoint != "" {
		env["entrypoint"] = entrypoint.String()
	}
	if existing, ok := payload["env"].(map[string]any); ok {
		for k, v := range existing {
			env[k] = v
		}
	}
	payload["env"] = env

	engine, err := policy.NewEngineFromPaths(policyPaths)
	if err != nil {
		return nil, err
	}
	actions, err := engine.EvaluateAll(ctx, payload, command, entrypoint.String())
	if err != nil {
		return nil, err
	}
	printWarnings := command != "scan"
	for _, act := range actions {
		switch act.Type {
		case "deny":
			msg := firstNonEmpty(act.Reason, act.Message, "policy denied execution")
			return nil, fmt.Errorf("policy %s denied command: %s", act.Source, msg)
		case "warn":
			if printWarnings {
				msg := firstNonEmpty(act.Reason, act.Message, "policy warning")
				fmt.Fprintf(errW, "policy warning (%s): %s\n", act.Source, msg)
			}
		case "allow", "":
			continue
		default:
			msg := firstNonEmpty(act.Reason, act.Message, "")
			if msg != "" {
				fmt.Fprintf(errW, "policy %s reported %s: %s\n", act.Source, act.Type, msg)
			}
		}
	}
	return actions, nil
}

// firstNonEmpty returns the first non-empty string from the provided values.
func firstNonEmpty(values ...string) string {
	for _, v := range values {
		if v = strings.TrimSpace(v); v != "" {
			return v
		}
	}
	return ""
}
