package cmd

import (
	"context"
	"fmt"
	"io"
	"os"
	"strings"

	policyv1 "github.com/temporalio/deputy/gen/deputy/policy/v1"
	"github.com/temporalio/deputy/internal/policy"
)

// policyEvaluator evaluates policy bundles repeatedly within a single command
// run, compiling the engine once instead of once per evaluation call.
//
// Unlike evaluatePoliciesForCommand it never prints: callers collect the
// returned actions and render them as one cohesive section after the report,
// instead of interleaving warnings with rendered output as evaluation
// happens.
type policyEvaluator struct {
	engine  *policy.Engine
	command string
}

// newPolicyEvaluator compiles the policy bundles at the given paths for
// repeated evaluation. It returns a nil evaluator (and no error) when no
// paths are given; the nil evaluator is safe to call and evaluates nothing.
func newPolicyEvaluator(policyPaths []string, command string) (*policyEvaluator, error) {
	if len(policyPaths) == 0 {
		return nil, nil
	}
	engine, err := policy.NewEngineFromPaths(policyPaths)
	if err != nil {
		return nil, err
	}
	return &policyEvaluator{engine: engine, command: command}, nil
}

// evaluate runs one entrypoint against the payload and returns the raw
// actions. It injects the env context (command, entrypoint) into the payload
// so rules can branch on where they run, matching the historical
// evaluatePoliciesForCommand behavior.
func (e *policyEvaluator) evaluate(ctx context.Context, payload map[string]any, entrypoint policy.Entrypoint) ([]policy.Action, error) {
	if e == nil {
		return nil, nil
	}
	if payload == nil {
		payload = map[string]any{}
	}
	payload["env"] = map[string]any{
		"command":    e.command,
		"entrypoint": entrypoint.String(),
	}
	return e.engine.EvaluateAllMap(ctx, payload, e.command, entrypoint.String())
}

// policyDenyError builds the blocking error for structured deny results, or
// nil when nothing denied. It exists so commands can finish rendering the
// full report and structured output before failing: the exit code still
// reflects the denial, but the user gets the complete picture first.
func policyDenyError(actions []*policyv1.Action) error {
	var denies []*policyv1.Action
	for _, act := range actions {
		if act.GetType() == policyv1.ActionType_ACTION_TYPE_DENY {
			denies = append(denies, act)
		}
	}
	if len(denies) == 0 {
		return nil
	}
	first := denies[0]
	source := first.GetPolicyName()
	if rule := first.GetRuleName(); rule != "" {
		source += "::" + rule
	}
	msg := firstNonEmpty(first.GetReason(), first.GetMessage(), "policy denied execution")
	if len(denies) == 1 {
		return fmt.Errorf("policy %s denied command: %s", source, msg)
	}
	return fmt.Errorf("policy %s denied command: %s (and %d more denial%s)", source, msg, len(denies)-1, plural(len(denies)-1))
}

// evaluatePoliciesForCommand evaluates the given policies against a command and payload.
// It returns a list of actions generated by the policies, or an error if a "deny" action is encountered.
// Warnings are printed to errW (or stderr if nil), unless the command is "scan".
//
// Deprecated for new call sites: prefer newPolicyEvaluator plus a rendered
// section from the collected results, so warnings do not interleave with
// command output. This wrapper preserves the print-as-you-go behavior for
// commands that still rely on it.
func evaluatePoliciesForCommand(ctx context.Context, policyPaths []string, payload map[string]any, command string, entrypoint policy.Entrypoint, errW io.Writer) ([]policy.Action, error) {
	if errW == nil {
		errW = os.Stderr
	}
	evaluator, err := newPolicyEvaluator(policyPaths, command)
	if evaluator == nil || err != nil {
		return nil, err
	}
	actions, err := evaluator.evaluate(ctx, payload, entrypoint)
	if err != nil {
		return nil, err
	}
	printWarnings := command != "scan"
	for _, act := range actions {
		switch act.Type {
		case "deny":
			msg := firstNonEmpty(act.Reason, act.Message, "policy denied execution")
			return nil, fmt.Errorf("policy %s denied command: %s", act.Source, msg)
		case "warn":
			if printWarnings {
				msg := firstNonEmpty(act.Reason, act.Message, "policy warning")
				fmt.Fprintf(errW, "policy warning (%s): %s\n", act.Source, msg)
			}
		case "allow", "":
			continue
		default:
			msg := firstNonEmpty(act.Reason, act.Message, "")
			if msg != "" {
				fmt.Fprintf(errW, "policy %s reported %s: %s\n", act.Source, act.Type, msg)
			}
		}
	}
	return actions, nil
}

// firstNonEmpty returns the first non-empty string from the provided values.
func firstNonEmpty(values ...string) string {
	for _, v := range values {
		if v = strings.TrimSpace(v); v != "" {
			return v
		}
	}
	return ""
}
