package mise

import (
	"slices"
	"strings"
	"testing"
)

func TestPruneLockedVersions(t *testing.T) {
	const lock = `# @generated - this file is auto-generated by ` + "`mise lock`" + `
[[tools.go]]
version = "1.22.12"
backend = "core:go"

[tools.go.platforms.linux-x64]
checksum = "sha256:oldgo"
size = 123

[[tools.go]]
version = "1.23.8"
backend = "core:go"

[tools.go.platforms.linux-x64]
checksum = "sha256:othergo"

[[tools."npm:lodash"]]
version = "4.17.20"
backend = "npm:lodash"

[tools."npm:lodash"."platforms.linux-x64"]
checksum = "sha256:lodash"

[[tools.node]]
version = "20.11.0"
backend = "core:node"
`

	tests := []struct {
		name        string
		toolKeys    []string
		stale       []string
		wantChanged bool
		wantGone    []string
		wantKept    []string
	}{
		{
			name:        "prunes one stale entry and its platforms",
			toolKeys:    []string{"go"},
			stale:       []string{"1.22.12"},
			wantChanged: true,
			wantGone:    []string{"1.22.12", "sha256:oldgo"},
			wantKept:    []string{"1.23.8", "sha256:othergo", "4.17.20", "20.11.0", "@generated"},
		},
		{
			name:        "prunes multiple stale entries",
			toolKeys:    []string{"go"},
			stale:       []string{"1.22.12", "1.23.8"},
			wantChanged: true,
			wantGone:    []string{"1.22.12", "1.23.8", "sha256:oldgo", "sha256:othergo"},
			wantKept:    []string{"4.17.20", "20.11.0"},
		},
		{
			name:        "quoted backend-prefixed key with dotted platform tables",
			toolKeys:    []string{"npm:lodash", "lodash"},
			stale:       []string{"4.17.20"},
			wantChanged: true,
			wantGone:    []string{"4.17.20", "sha256:lodash"},
			wantKept:    []string{"1.22.12", "1.23.8", "20.11.0"},
		},
		{
			name:        "no matching version leaves content untouched",
			toolKeys:    []string{"go"},
			stale:       []string{"9.9.9"},
			wantChanged: false,
		},
		{
			name:        "unknown tool leaves content untouched",
			toolKeys:    []string{"terraform"},
			stale:       []string{"1.22.12"},
			wantChanged: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, changed := PruneLockedVersions([]byte(lock), tt.toolKeys, func(v string) bool {
				return slices.Contains(tt.stale, v)
			})
			if changed != tt.wantChanged {
				t.Fatalf("changed = %v, want %v\n%s", changed, tt.wantChanged, got)
			}
			if !changed {
				if string(got) != lock {
					t.Fatal("content modified despite changed=false")
				}
				return
			}
			for _, s := range tt.wantGone {
				if strings.Contains(string(got), s) {
					t.Errorf("stale marker %q survived:\n%s", s, got)
				}
			}
			for _, s := range tt.wantKept {
				if !strings.Contains(string(got), s) {
					t.Errorf("expected %q to survive:\n%s", s, got)
				}
			}
			if strings.Contains(string(got), "\n\n\n") {
				t.Errorf("pruning left doubled blank lines:\n%s", got)
			}
			// The pruned lockfile must still parse.
			if _, err := ParseLock("mise.lock", got); err != nil {
				t.Errorf("pruned lockfile no longer parses: %v", err)
			}
		})
	}
}

// TestPruneLockedVersionsKeepsTrailingTrivia pins that comments and blank
// lines between a pruned entry and the next one stay with the entry they
// introduce. Deleting them would silently drop annotations belonging to a
// surviving entry, which the function promises to preserve byte-for-byte.
func TestPruneLockedVersionsKeepsTrailingTrivia(t *testing.T) {
	tests := []struct {
		name     string
		lock     string
		want     string
		toolKeys []string
		stale    string
	}{
		{
			name: "comment above the next entry survives",
			lock: `[[tools.go]]
version = "1.22.12"
backend = "core:go"

# node is pinned by the platform team, do not bump
[[tools.node]]
version = "20.11.0"
`,
			want: `# node is pinned by the platform team, do not bump
[[tools.node]]
version = "20.11.0"
`,
			toolKeys: []string{"go"}, stale: "1.22.12",
		},
		{
			name: "comment survives when the pruned entry is in the middle",
			lock: `[[tools.node]]
version = "20.11.0"

[[tools.go]]
version = "1.22.12"

# ripgrep is vendored, keep this entry
[[tools.ripgrep]]
version = "14.1.1"
`,
			want: `[[tools.node]]
version = "20.11.0"

# ripgrep is vendored, keep this entry
[[tools.ripgrep]]
version = "14.1.1"
`,
			toolKeys: []string{"go"}, stale: "1.22.12",
		},
		{
			name: "header comment of the pruned entry goes with it",
			lock: `# go is stale
[[tools.go]]
version = "1.22.12"

[[tools.node]]
version = "20.11.0"
`,
			// The comment above the pruned entry introduces it, so it is not
			// trailing trivia of a previous block and stays put.
			want: `# go is stale
[[tools.node]]
version = "20.11.0"
`,
			toolKeys: []string{"go"}, stale: "1.22.12",
		},
		{
			name: "trailing entry at end of file",
			lock: `[[tools.node]]
version = "20.11.0"

[[tools.go]]
version = "1.22.12"
`,
			want: `[[tools.node]]
version = "20.11.0"
`,
			toolKeys: []string{"go"}, stale: "1.22.12",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, changed := PruneLockedVersions([]byte(tt.lock), tt.toolKeys, func(v string) bool {
				return v == tt.stale
			})
			if !changed {
				t.Fatal("expected the stale entry to be pruned")
			}
			if string(got) != tt.want {
				t.Errorf("prune mismatch:\n--- got ---\n%s\n--- want ---\n%s", got, tt.want)
			}
			if _, err := ParseLock("mise.lock", got); err != nil {
				t.Errorf("pruned lockfile no longer parses: %v", err)
			}
		})
	}
}

// TestPruneLockedVersionsReadsVersionLikeTheParser pins that the pruner reads a
// lock entry's version the way [ParseLock] does. The two must agree: the plan
// carries the version inventory reported, which came from the parser, so a
// pruner that compares the raw bytes of an escaped token leaves the stale entry
// behind and the next scan reports the freshly fixed config at the old version.
//
// A token the pruner cannot decode is a version it cannot call stale, so the
// whole edit is refused rather than guessed at, even under a predicate that
// calls every other version stale.
func TestPruneLockedVersionsReadsVersionLikeTheParser(t *testing.T) {
	tests := []struct {
		name string
		// token is the text following `version = ` in the entry.
		token string
		// want is the version ParseLock decodes from token, or "" when the
		// lockfile does not parse at all.
		want string
		// prunable says whether the pruner may act on the entry.
		prunable bool
	}{
		{name: "basic string", token: `"1.22.12"`, want: "1.22.12", prunable: true},
		{name: "unicode escapes", token: `"1.22.\u0031\u0032"`, want: "1.22.12", prunable: true},
		{name: "short escape", token: `"1.22.1\x32"`, want: "1.22.12", prunable: true},
		{name: "literal string", token: `'1.22.12'`, want: "1.22.12", prunable: true},
		{name: "multi-line basic string", token: `"""1.22.12"""`, want: "1.22.12", prunable: true},
		{name: "multi-line literal string", token: `'''1.22.12'''`, want: "1.22.12", prunable: true},
		{name: "trailing comment", token: `"1.22.12" # pinned`, want: "1.22.12", prunable: true},
		// Undefined escapes make the file unreadable to the parser too, so
		// there is nothing here the pruner is entitled to delete.
		{name: "undefined escape", token: `"1.22.\q12"`, want: "", prunable: false},
		// The value continues on a line the pruner has not gathered, so it has
		// not seen the version and must not act on the entry.
		// The multiline gathering added for header-shaped string content must not
		// turn any of these into a silent skip: a version the pruner cannot read
		// on the line that declares it is a version it cannot call stale,
		// whichever quoting form carries the value past the end of the line.
		{name: "value spanning lines", token: "\"\"\"\n1.22.12\"\"\"", want: "1.22.12", prunable: false},
		{name: "literal value spanning lines", token: "'''\n1.22.12'''", want: "1.22.12", prunable: false},
		{name: "value spanning lines after content", token: "\"\"\"1.22.12\n\"\"\"", want: "1.22.12\n", prunable: false},
		{name: "unterminated string", token: `"1.22.12`, want: "", prunable: false},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			lock := "[[tools.go]]\nversion = " + tt.token + "\nbackend = \"core:go\"\n"
			if tt.want != "" {
				lf, err := ParseLock("mise.lock", []byte(lock))
				if err != nil {
					t.Fatalf("ParseLock: %v", err)
				}
				if got := lf.Tools["go"][0].Version; got != tt.want {
					t.Fatalf("ParseLock version = %q, want %q", got, tt.want)
				}
			}

			got, changed := PruneLockedVersions([]byte(lock), []string{"go"}, func(v string) bool {
				return v == tt.want
			})
			if changed != tt.prunable {
				t.Fatalf("prune of %s: changed = %v, want %v\n%s", tt.want, changed, tt.prunable, got)
			}
			if changed && strings.Contains(string(got), "core:go") {
				t.Errorf("stale entry survived:\n%s", got)
			}

			// The remediation path with no known current versions calls every
			// version but the new one stale. An unreadable version must still
			// not be deleted on that predicate.
			got, changed = PruneLockedVersions([]byte(lock), []string{"go"}, func(string) bool { return true })
			if changed != tt.prunable {
				t.Fatalf("catch-all prune: changed = %v, want %v\n%s", changed, tt.prunable, got)
			}
			if !changed && string(got) != lock {
				t.Errorf("content modified despite changed=false:\n%s", got)
			}
		})
	}
}

// TestPruneLockedVersionsReadsVersionKeyLikeTheParser pins that the pruner
// identifies the version assignment by the key a TOML parser reads, not by the
// bytes before the `=`. TOML lets a bare key be spelled as a quoted one, and
// [ParseLock] decodes `"version" = "1.22.12"` to 1.22.12 like any other
// spelling. A literal comparison reads that line as unrelated, which fails in
// both directions: with known current versions the entry is never called stale
// and survives to be served back after the fix, and with the catch-all
// predicate remediation uses when no current version is known, the entry is
// deleted on a version the pruner never read.
func TestPruneLockedVersionsReadsVersionKeyLikeTheParser(t *testing.T) {
	tests := []struct {
		name string
		// key is the text before `=` in the entry's version assignment.
		key string
		// wantVersion is the version the pruner must hand its predicate, which
		// is the one ParseLock decodes. It is "" when the line does not
		// declare the entry's version at all.
		wantVersion string
	}{
		{name: "bare key", key: `version`, wantVersion: "1.22.12"},
		{name: "basic-string key", key: `"version"`, wantVersion: "1.22.12"},
		{name: "literal-string key", key: `'version'`, wantVersion: "1.22.12"},
		{name: "escaped key", key: `"\u0076ersion"`, wantVersion: "1.22.12"},
		{name: "padded key", key: "  version\t", wantVersion: "1.22.12"},
		// Keys that are not the entry's version must stay unread, or an
		// unrelated field decides whether integrity metadata is deleted.
		{name: "another key", key: `versions`},
		{name: "dotted key", key: `platforms.version`},
		{name: "quoted key holding an equals sign", key: `"ver=sion"`},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			lock := "[[tools.go]]\n" + tt.key + " = \"1.22.12\"\nbackend = \"core:go\"\n"
			if tt.wantVersion != "" {
				lf, err := ParseLock("mise.lock", []byte(lock))
				if err != nil {
					t.Fatalf("ParseLock: %v", err)
				}
				if got := lf.Tools["go"][0].Version; got != tt.wantVersion {
					t.Fatalf("ParseLock version = %q, want %q", got, tt.wantVersion)
				}
			}

			var seen []string
			_, changed := PruneLockedVersions([]byte(lock), []string{"go"}, func(v string) bool {
				seen = append(seen, v)
				return v == "1.22.12"
			})
			if want := []string{tt.wantVersion}; !slices.Equal(seen, want) {
				t.Errorf("predicate saw %q, want %q", seen, want)
			}
			if wantPruned := tt.wantVersion == "1.22.12"; changed != wantPruned {
				t.Errorf("changed = %v, want %v", changed, wantPruned)
			}
		})
	}
}

// TestPruneLockedVersionsReadsHeaderKeyLikeTheParser pins that the pruner finds
// the end of a lock table header outside the header's quoted key segments. A
// mise tool key carries option syntax in brackets, and TOML lets any of those
// characters sit inside a quoted key, so the first "]]" in the line is not
// necessarily the one closing the header.
//
// Cutting the header at it fails in both directions. The entry whose key holds
// the delimiters is never recognized, so its stale version survives a fix that
// reports success and the next scan reports the vulnerable version again. Worse,
// an unrecognized header does not end the preceding entry either, so pruning a
// neighbour swallows the whole entry after it and deletes the integrity metadata
// of a tool nobody edited.
//
// Every key here is one [Parse] and [ParseLock] decode, which the cases assert
// before pruning: the pruner has to act on the lockfiles Deputy itself reads.
func TestPruneLockedVersionsReadsHeaderKeyLikeTheParser(t *testing.T) {
	const bracketed = `ubi:owner/repo[opt=[x]]`
	bracketedEntry := "[[tools.\"" + bracketed + "\"]]\n" +
		"version = \"1.22.12\"\nbackend = \"ubi:owner/repo\"\n\n" +
		"[tools.\"" + bracketed + "\".\"platforms.linux-x64\"]\nchecksum = \"sha256:bracketed\"\n"
	const nodeEntry = "[[tools.node]]\nversion = \"20.11.0\"\nbackend = \"core:node\"\n"

	tests := []struct {
		name     string
		lock     string
		toolKeys []string
		stale    string
		want     string
	}{
		{
			// The entry Deputy has to prune is the one with the bracketed key.
			name:     "delimiters inside the pruned entry's key",
			lock:     bracketedEntry + "\n" + nodeEntry,
			toolKeys: []string{bracketed, "owner/repo"},
			stale:    "1.22.12",
			want:     nodeEntry,
		},
		{
			// The bracketed key belongs to the following entry, which must
			// survive intact: its header ends the entry being pruned.
			name:     "delimiters inside the following entry's key",
			lock:     nodeEntry + "\n" + bracketedEntry,
			toolKeys: []string{"node"},
			stale:    "20.11.0",
			want:     bracketedEntry,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			lf, err := ParseLock("mise.lock", []byte(tt.lock))
			if err != nil {
				t.Fatalf("ParseLock: %v", err)
			}
			if len(lf.Tools[bracketed]) != 1 {
				t.Fatalf("ParseLock read %d entries for %q, want 1", len(lf.Tools[bracketed]), bracketed)
			}
			cfg, err := Parse("mise.toml", []byte("[tools]\n\""+bracketed+"\" = \"1.22.12\"\n"))
			if err != nil {
				t.Fatalf("Parse: %v", err)
			}
			if len(cfg.Tools) != 1 || cfg.Tools[0].Key != bracketed {
				t.Fatalf("Parse read tools %+v, want the single key %q", cfg.Tools, bracketed)
			}

			got, changed := PruneLockedVersions([]byte(tt.lock), tt.toolKeys, func(v string) bool {
				return v == tt.stale
			})
			if !changed {
				t.Fatalf("expected the stale entry to be pruned:\n%s", got)
			}
			if string(got) != tt.want {
				t.Errorf("prune mismatch:\n--- got ---\n%s\n--- want ---\n%s", got, tt.want)
			}
			if _, err := ParseLock("mise.lock", got); err != nil {
				t.Errorf("pruned lockfile no longer parses: %v", err)
			}
		})
	}
}

func TestSplitKeyPath(t *testing.T) {
	tests := []struct {
		key  string
		want []string
	}{
		{"tools", []string{"tools"}},
		{"tools.go", []string{"tools", "go"}},
		{"tools.go.version", []string{"tools", "go", "version"}},
		{`tools."npm:lodash"`, []string{"tools", "npm:lodash"}},
		{`tools."npm:lodash".version`, []string{"tools", "npm:lodash", "version"}},
		{`tools."aqua:owner/repo"."platforms.linux-x64"`, []string{"tools", "aqua:owner/repo", "platforms.linux-x64"}},
		{`tools . go`, []string{"tools", "go"}},
		{"", nil},
		{"tools..go", nil},
		{`tools."unterminated`, nil},
		// Basic strings are decoded, the way the TOML parser behind Parse
		// decodes them, so an escaped key names the same tool it inventories.
		{`tools."go"`, []string{"tools", "go"}},
		{`tools."g\U0000006f".version`, []string{"tools", "go", "version"}},
		{`tools."g\x6f"`, []string{"tools", "go"}},
		{`tools."npm:lodash".version`, []string{"tools", "npm:lodash", "version"}},
		{`"tools".go`, []string{"tools", "go"}},
		// An escaped quote belongs to the segment; it does not end it.
		{`tools."a\"b".version`, []string{"tools", `a"b`, "version"}},
		{`tools."a\\".version`, []string{"tools", `a\`, "version"}},
		// Literal strings carry no escapes.
		{`tools.'go'`, []string{"tools", `go`}},
		// Escapes TOML does not define, and truncated ones, are refused
		// rather than matched as raw bytes.
		{`tools."a\/b"`, nil},
		{`tools."a\q"`, nil},
		{`tools."a\u00"`, nil},
		{`tools."a\uD800"`, nil},
		{`tools."a\`, nil},
	}
	for _, tt := range tests {
		t.Run(tt.key, func(t *testing.T) {
			if got := SplitKeyPath(tt.key); !slices.Equal(got, tt.want) {
				t.Errorf("SplitKeyPath(%q) = %v, want %v", tt.key, got, tt.want)
			}
		})
	}
}

func TestUnquoteTOMLString(t *testing.T) {
	tests := []struct {
		token string
		want  string
	}{
		{`"1.22.12"`, "1.22.12"},
		{`'1.22.12'`, "1.22.12"},
		{"1.22.12", "1.22.12"},
		{`"1.22.12"`, "1.22.12"},
		{`"a\"b"`, `a"b`},
		{`'ab'`, `ab`},
		{"", ""},
		{`"`, `"`},
		// Unterminated, trailing junk, and undefined escapes leave the token
		// as written so nothing is matched on a half-decoded value.
		{`"unterminated`, `"unterminated`},
		{`"a" trailing`, `"a" trailing`},
		{`"a\/b"`, `"a\/b"`},
		{`'a'b'`, `'a'b'`},
		// Multi-line strings: TOML's other two string forms. A tool may write
		// a version with either, and mise reads them as ordinary scalars.
		{`"""1.22.12"""`, "1.22.12"},
		{`'''1.22.12'''`, "1.22.12"},
		{"\"\"\"\n1.22.12\"\"\"", "1.22.12"}, // a newline right after the opener is dropped
		{"'''\n1.22.12'''", "1.22.12"},
		{`"""a\"b"""`, `a"b`},
		{`""""quoted""""`, `"quoted"`},            // one adjacent quote is content
		{"\"\"\"1.22.\\\n   12\"\"\"", "1.22.12"}, // a trailing backslash swallows the line break
		// Refused the same way the single-line forms are: an unterminated
		// token, trailing junk, or a second key smuggled in after the string.
		{`"""unterminated`, `"""unterminated`},
		{`'''unterminated`, `'''unterminated`},
		{`"""a""" trailing`, `"""a""" trailing`},
		{"\"\"\"a\"\"\"\nother = 1", "\"\"\"a\"\"\"\nother = 1"},
		{`"""a\/b"""`, `"""a\/b"""`},
	}
	for _, tt := range tests {
		t.Run(tt.token, func(t *testing.T) {
			if got := UnquoteTOMLString(tt.token); got != tt.want {
				t.Errorf("UnquoteTOMLString(%q) = %q, want %q", tt.token, got, tt.want)
			}
		})
	}
}

// TestPruneLockedVersionsSkipsMultilineStringContent pins that the pruner reads
// a lockfile's structure and not the prose inside it. A lock entry may carry a
// multi-line string, and TOML puts no restriction on its content: a field
// holding release notes or a diff can contain a line reading `[[tools.go]]`.
//
// A line-wise scan took such a line for the start of the next entry, which broke
// the file in two directions. Pruning the entry the string belongs to deleted
// only the lines above it and left the closing delimiter behind, and a fake
// header naming the tool being pruned made the pruner delete the tail of an
// entry that had to survive. Either way [ParseLock] accepts the original file
// and rejects the result, so a fix reports success and leaves a lockfile mise
// cannot read.
func TestPruneLockedVersionsSkipsMultilineStringContent(t *testing.T) {
	tests := []struct {
		name     string
		lock     string
		toolKeys []string
		stale    string
		// want is the expected content; wantChanged false means the file must
		// come back byte for byte.
		want        string
		wantChanged bool
	}{
		{
			// The string belongs to the entry being pruned, so it goes with it,
			// delimiters and all.
			name: "a header inside the pruned entry's own string",
			lock: `[[tools.go]]
version = "1.22.12"
notes = """
[[tools.node]]
version = "20.11.0"
"""

[[tools.ripgrep]]
version = "14.1.1"
`,
			toolKeys: []string{"go"}, stale: "1.22.12",
			want: `[[tools.ripgrep]]
version = "14.1.1"
`,
			wantChanged: true,
		},
		{
			// The only mention of the pruned tool is inside another entry's
			// string, so there is no entry to prune and nothing may be touched.
			name: "a header inside a surviving entry's string",
			lock: `[[tools.node]]
version = "20.11.0"
notes = """
[[tools.go]]
version = "1.22.12"
"""
`,
			toolKeys: []string{"go"}, stale: "1.22.12",
		},
		{
			// The version of the entry being pruned is real, and the string
			// after it merely mentions another one.
			name: "a stale entry is still pruned around its string",
			lock: `[[tools.node]]
version = "20.11.0"

[[tools.go]]
version = "1.22.12"
notes = """
version = "9.9.9"
[[tools.go]]
"""
`,
			toolKeys: []string{"go"}, stale: "1.22.12",
			want: `[[tools.node]]
version = "20.11.0"
`,
			wantChanged: true,
		},
		{
			// The entry's own version still decides staleness when a string
			// field precedes it: the skip must not carry the scan past the
			// version line, and a `version` written inside the string is not
			// the entry's.
			name: "a string field before the version",
			lock: `[[tools.node]]
version = "20.11.0"

[[tools.go]]
notes = """
version = "9.9.9"
"""
version = "1.22.12"
`,
			toolKeys: []string{"go"}, stale: "1.22.12",
			want: `[[tools.node]]
version = "20.11.0"
`,
			wantChanged: true,
		},
		{
			// A string that never closes leaves the extent of everything after
			// it unknown, so the edit is abandoned rather than guessed at.
			name: "an unterminated string abandons the edit",
			lock: `[[tools.go]]
version = "1.22.12"
notes = """
[[tools.node]]
`,
			toolKeys: []string{"go"}, stale: "1.22.12",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			// Every fixture but the unterminated one is a lockfile the parser
			// reads, so the pruner is being held to the same file it does.
			_, parseErr := ParseLock("mise.lock", []byte(tt.lock))
			if !strings.Contains(tt.name, "unterminated") && parseErr != nil {
				t.Fatalf("fixture does not parse: %v", parseErr)
			}

			got, changed := PruneLockedVersions([]byte(tt.lock), tt.toolKeys, func(v string) bool {
				return v == tt.stale
			})
			if changed != tt.wantChanged {
				t.Fatalf("changed = %v, want %v:\n%s", changed, tt.wantChanged, got)
			}
			want := tt.want
			if !tt.wantChanged {
				want = tt.lock
			}
			if string(got) != want {
				t.Errorf("prune mismatch:\n--- got ---\n%s\n--- want ---\n%s", got, want)
			}
			if parseErr == nil {
				if _, err := ParseLock("mise.lock", got); err != nil {
					t.Errorf("pruned lockfile no longer parses: %v\n%s", err, got)
				}
			}
		})
	}
}

// TestPruneLockedVersionsKeepsNestedTablesWithTheirEntry pins what belongs to a
// lock entry. TOML attaches a nested array of tables, [[tools.go.metadata]], to
// the entry above it exactly as a single-bracket [tools.go.platforms.linux-x64]
// table is attached, and mise still resolves the parent's locked version. The
// boundary scan ended an entry at any array header, so pruning a stale entry
// left its own nested tables behind: the file then opened with
// [[tools.go.metadata]], which makes tools.go a table rather than an array of
// them, and [ParseLock] rejects a lockfile it accepted before the edit. Every
// tool in that file loses its locked versions and checksums with it.
func TestPruneLockedVersionsKeepsNestedTablesWithTheirEntry(t *testing.T) {
	tests := []struct {
		name     string
		lock     string
		toolKeys []string
		stale    string
		want     string
	}{
		{
			// The nested table belongs to the pruned entry, so it goes too.
			name: "a nested array table under the pruned entry",
			lock: `[[tools.go]]
version = "1.22.12"
backend = "core:go"

[[tools.go.metadata]]
source = "release"

[[tools.node]]
version = "20.11.0"
`,
			toolKeys: []string{"go"}, stale: "1.22.12",
			want: `[[tools.node]]
version = "20.11.0"
`,
		},
		{
			// Several nested tables, and a single-bracket one among them.
			name: "nested tables of both bracket forms",
			lock: `[[tools.go]]
version = "1.22.12"

[[tools.go.metadata]]
source = "release"

[tools.go.platforms.linux-x64]
checksum = "sha256:oldgo"

[[tools.go.metadata]]
source = "mirror"

[[tools.node]]
version = "20.11.0"
`,
			toolKeys: []string{"go"}, stale: "1.22.12",
			want: `[[tools.node]]
version = "20.11.0"
`,
		},
		{
			// The next entry of the same tool still ends the current one, so a
			// surviving sibling keeps its own nested tables.
			name: "the next entry of the same tool ends the current one",
			lock: `[[tools.go]]
version = "1.22.12"

[[tools.go.metadata]]
source = "release"

[[tools.go]]
version = "1.23.8"

[[tools.go.metadata]]
source = "kept"
`,
			toolKeys: []string{"go"}, stale: "1.22.12",
			want: `[[tools.go]]
version = "1.23.8"

[[tools.go.metadata]]
source = "kept"
`,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			// The premise: this is a lockfile the parser reads, at the version
			// the pruner is asked about.
			lf, err := ParseLock("mise.lock", []byte(tt.lock))
			if err != nil {
				t.Fatalf("fixture does not parse: %v", err)
			}
			if len(lf.Tools["go"]) == 0 || lf.Tools["go"][0].Version != tt.stale {
				t.Fatalf("fixture locks go at %+v, want %q first", lf.Tools["go"], tt.stale)
			}

			got, changed := PruneLockedVersions([]byte(tt.lock), tt.toolKeys, func(v string) bool {
				return v == tt.stale
			})
			if !changed {
				t.Fatalf("expected the stale entry to be pruned:\n%s", got)
			}
			if string(got) != tt.want {
				t.Errorf("prune mismatch:\n--- got ---\n%s\n--- want ---\n%s", got, tt.want)
			}
			// The file has to stay one mise can read, which is the whole point.
			if _, err := ParseLock("mise.lock", got); err != nil {
				t.Errorf("pruned lockfile no longer parses: %v\n%s", err, got)
			}
		})
	}
}
