package mise

import (
	"slices"
	"strings"
	"testing"
)

func TestPruneLockedVersions(t *testing.T) {
	const lock = `# @generated - this file is auto-generated by ` + "`mise lock`" + `
[[tools.go]]
version = "1.22.12"
backend = "core:go"

[tools.go.platforms.linux-x64]
checksum = "sha256:oldgo"
size = 123

[[tools.go]]
version = "1.23.8"
backend = "core:go"

[tools.go.platforms.linux-x64]
checksum = "sha256:othergo"

[[tools."npm:lodash"]]
version = "4.17.20"
backend = "npm:lodash"

[tools."npm:lodash"."platforms.linux-x64"]
checksum = "sha256:lodash"

[[tools.node]]
version = "20.11.0"
backend = "core:node"
`

	tests := []struct {
		name        string
		toolKeys    []string
		stale       []string
		wantChanged bool
		wantGone    []string
		wantKept    []string
	}{
		{
			name:        "prunes one stale entry and its platforms",
			toolKeys:    []string{"go"},
			stale:       []string{"1.22.12"},
			wantChanged: true,
			wantGone:    []string{"1.22.12", "sha256:oldgo"},
			wantKept:    []string{"1.23.8", "sha256:othergo", "4.17.20", "20.11.0", "@generated"},
		},
		{
			name:        "prunes multiple stale entries",
			toolKeys:    []string{"go"},
			stale:       []string{"1.22.12", "1.23.8"},
			wantChanged: true,
			wantGone:    []string{"1.22.12", "1.23.8", "sha256:oldgo", "sha256:othergo"},
			wantKept:    []string{"4.17.20", "20.11.0"},
		},
		{
			name:        "quoted backend-prefixed key with dotted platform tables",
			toolKeys:    []string{"npm:lodash", "lodash"},
			stale:       []string{"4.17.20"},
			wantChanged: true,
			wantGone:    []string{"4.17.20", "sha256:lodash"},
			wantKept:    []string{"1.22.12", "1.23.8", "20.11.0"},
		},
		{
			name:        "no matching version leaves content untouched",
			toolKeys:    []string{"go"},
			stale:       []string{"9.9.9"},
			wantChanged: false,
		},
		{
			name:        "unknown tool leaves content untouched",
			toolKeys:    []string{"terraform"},
			stale:       []string{"1.22.12"},
			wantChanged: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, changed := PruneLockedVersions([]byte(lock), tt.toolKeys, func(v string) bool {
				return slices.Contains(tt.stale, v)
			})
			if changed != tt.wantChanged {
				t.Fatalf("changed = %v, want %v\n%s", changed, tt.wantChanged, got)
			}
			if !changed {
				if string(got) != lock {
					t.Fatal("content modified despite changed=false")
				}
				return
			}
			for _, s := range tt.wantGone {
				if strings.Contains(string(got), s) {
					t.Errorf("stale marker %q survived:\n%s", s, got)
				}
			}
			for _, s := range tt.wantKept {
				if !strings.Contains(string(got), s) {
					t.Errorf("expected %q to survive:\n%s", s, got)
				}
			}
			if strings.Contains(string(got), "\n\n\n") {
				t.Errorf("pruning left doubled blank lines:\n%s", got)
			}
			// The pruned lockfile must still parse.
			if _, err := ParseLock("mise.lock", got); err != nil {
				t.Errorf("pruned lockfile no longer parses: %v", err)
			}
		})
	}
}

func TestHasLockedTool(t *testing.T) {
	const lock = `[[tools."npm:node"]]
version = "20.11.0"

[tools."npm:node"."platforms.linux-x64"]
checksum = "sha256:npmnode"

[[tools.go]]
version = "1.22.12"
`
	tests := []struct {
		key  string
		want bool
	}{
		{"npm:node", true},
		{"go", true},
		// Only array-of-tables entry headers count, not platform sub-tables.
		{"node", false},
		{"terraform", false},
		{"", false},
	}
	for _, tt := range tests {
		t.Run(tt.key, func(t *testing.T) {
			if got := HasLockedTool([]byte(lock), tt.key); got != tt.want {
				t.Errorf("HasLockedTool(%q) = %v, want %v", tt.key, got, tt.want)
			}
		})
	}
}

func TestSplitKeyPath(t *testing.T) {
	tests := []struct {
		key  string
		want []string
	}{
		{"tools", []string{"tools"}},
		{"tools.go", []string{"tools", "go"}},
		{"tools.go.version", []string{"tools", "go", "version"}},
		{`tools."npm:lodash"`, []string{"tools", "npm:lodash"}},
		{`tools."npm:lodash".version`, []string{"tools", "npm:lodash", "version"}},
		{`tools."aqua:owner/repo"."platforms.linux-x64"`, []string{"tools", "aqua:owner/repo", "platforms.linux-x64"}},
		{`tools . go`, []string{"tools", "go"}},
		{"", nil},
		{"tools..go", nil},
		{`tools."unterminated`, nil},
	}
	for _, tt := range tests {
		t.Run(tt.key, func(t *testing.T) {
			if got := SplitKeyPath(tt.key); !slices.Equal(got, tt.want) {
				t.Errorf("SplitKeyPath(%q) = %v, want %v", tt.key, got, tt.want)
			}
		})
	}
}
