package mise

import "testing"

const sampleLock = `
[[tools.node]]
version = "20.11.0"
backend = "core:node"

[tools.node.platforms.linux-x64]
checksum = "sha256:aaa"
size = 23456789
url = "https://nodejs.org/dist/v20.11.0/node-v20.11.0-linux-x64.tar.xz"

[tools.node.platforms.macos-arm64]
checksum = "sha256:bbb"

[[tools.ripgrep]]
version = "14.1.1"
backend = "aqua:BurntSushi/ripgrep"
options = { exe = "rg" }

[tools.ripgrep.platforms.linux-x64]
checksum = "sha256:ccc"
size = 1234567
`

func TestParseLock(t *testing.T) {
	lf, err := ParseLock("mise.lock", []byte(sampleLock))
	if err != nil {
		t.Fatalf("ParseLock: %v", err)
	}

	node := lf.Locked("node", "20.11.0")
	if node == nil {
		t.Fatal("node@20.11.0 not found")
	}
	if node.Backend != "core:node" {
		t.Errorf("node backend = %q", node.Backend)
	}
	sums := node.Checksums()
	if sums["linux-x64"] != "sha256:aaa" || sums["macos-arm64"] != "sha256:bbb" {
		t.Errorf("node checksums = %v", sums)
	}
	if node.Platforms["linux-x64"].Size != 23456789 {
		t.Errorf("node linux-x64 size = %d", node.Platforms["linux-x64"].Size)
	}

	rg := lf.Locked("ripgrep", "14.1.1")
	if rg == nil {
		t.Fatal("ripgrep not found")
	}
	if rg.Options["exe"] != "rg" {
		t.Errorf("ripgrep options = %v", rg.Options)
	}

	if lf.Locked("node", "99.0.0") != nil {
		t.Error("unexpected match for non-existent version")
	}
	if lf.First("ripgrep").Version != "14.1.1" {
		t.Errorf("First(ripgrep) = %v", lf.First("ripgrep"))
	}
	if lf.First("missing") != nil {
		t.Error("First(missing) should be nil")
	}
	if lf.Sole("ripgrep").Version != "14.1.1" {
		t.Errorf("Sole(ripgrep) = %v", lf.Sole("ripgrep"))
	}
}

// realLock mirrors the structure mise actually emits: a backend-qualified,
// quoted tool key and per-platform data under a single quoted dotted key
// ("platforms.<os-arch>") rather than a nested platforms table. Verified
// against temporalio/saas-temporal's committed mise.lock.
const realLock = `# @generated - this file is auto-generated by ` + "`mise lock`" + `
[[tools."aqua:protocolbuffers/protobuf/protoc"]]
version = "33.1"
backend = "aqua:protocolbuffers/protobuf/protoc"

[tools."aqua:protocolbuffers/protobuf/protoc"."platforms.linux-x64"]
checksum = "sha256:f3340e28"
size = 123
url = "https://example/protoc-linux.zip"

[tools."aqua:protocolbuffers/protobuf/protoc"."platforms.macos-arm64"]
checksum = "sha256:db7e66ff"
url = "https://example/protoc-macos.zip"

[[tools.go]]
version = "1.26.3"
backend = "core:go"
`

func TestParseLockRealFormat(t *testing.T) {
	lf, err := ParseLock("mise.lock", []byte(realLock))
	if err != nil {
		t.Fatalf("ParseLock: %v", err)
	}
	protoc := lf.Locked("aqua:protocolbuffers/protobuf/protoc", "33.1")
	if protoc == nil {
		t.Fatal("protoc entry not found under backend-qualified key")
	}
	sums := protoc.Checksums()
	if sums["linux-x64"] != "sha256:f3340e28" || sums["macos-arm64"] != "sha256:db7e66ff" {
		t.Errorf("dotted-key platform checksums not captured: %v", sums)
	}
	if protoc.Platforms["linux-x64"].Size != 123 || protoc.Platforms["linux-x64"].URL == "" {
		t.Errorf("platform size/url not captured: %+v", protoc.Platforms["linux-x64"])
	}
	// A core tool with no platform assets still parses (no checksums).
	if g := lf.Locked("go", "1.26.3"); g == nil || g.Checksums() != nil {
		t.Errorf("go entry = %+v", g)
	}
}

func TestParseLockEmpty(t *testing.T) {
	lf, err := ParseLock("mise.lock", []byte(""))
	if err != nil {
		t.Fatalf("ParseLock empty: %v", err)
	}
	if len(lf.Tools) != 0 {
		t.Errorf("expected no tools, got %d", len(lf.Tools))
	}
	if lf.Locked("x", "1") != nil || lf.First("x") != nil || lf.Sole("x") != nil {
		t.Error("lookups on empty lock should be nil")
	}
}

func TestLockfileLookupAmbiguousFuzzyVersion(t *testing.T) {
	const data = `
[[tools.python]]
version = "3.11.9"

[[tools.python]]
version = "3.12.3"
`
	lf, err := ParseLock("mise.lock", []byte(data))
	if err != nil {
		t.Fatalf("ParseLock: %v", err)
	}

	if got := lf.Lookup(ToolSpec{Name: "python", Key: "python"}, "3.11.9", nil); got == nil || got.Version != "3.11.9" {
		t.Fatalf("exact lookup = %+v, want 3.11.9", got)
	}
	if got := lf.Lookup(ToolSpec{Name: "python", Key: "python"}, "3", nil); got != nil {
		t.Fatalf("ambiguous fuzzy lookup = %+v, want nil", got)
	}
	if got := lf.Sole("python"); got != nil {
		t.Fatalf("Sole(python) = %+v, want nil for multiple entries", got)
	}
}
