package mise

import (
	"slices"
	"strings"
	"testing"
)

func TestPruneLockedVersions(t *testing.T) {
	const lock = `# @generated - this file is auto-generated by ` + "`mise lock`" + `
[[tools.go]]
version = "1.22.12"
backend = "core:go"

[tools.go.platforms.linux-x64]
checksum = "sha256:oldgo"
size = 123

[[tools.go]]
version = "1.23.8"
backend = "core:go"

[tools.go.platforms.linux-x64]
checksum = "sha256:othergo"

[[tools."npm:lodash"]]
version = "4.17.20"
backend = "npm:lodash"

[tools."npm:lodash"."platforms.linux-x64"]
checksum = "sha256:lodash"

[[tools.node]]
version = "20.11.0"
backend = "core:node"
`

	tests := []struct {
		name        string
		toolKeys    []string
		stale       []string
		wantChanged bool
		wantGone    []string
		wantKept    []string
	}{
		{
			name:        "prunes one stale entry and its platforms",
			toolKeys:    []string{"go"},
			stale:       []string{"1.22.12"},
			wantChanged: true,
			wantGone:    []string{"1.22.12", "sha256:oldgo"},
			wantKept:    []string{"1.23.8", "sha256:othergo", "4.17.20", "20.11.0", "@generated"},
		},
		{
			name:        "prunes multiple stale entries",
			toolKeys:    []string{"go"},
			stale:       []string{"1.22.12", "1.23.8"},
			wantChanged: true,
			wantGone:    []string{"1.22.12", "1.23.8", "sha256:oldgo", "sha256:othergo"},
			wantKept:    []string{"4.17.20", "20.11.0"},
		},
		{
			name:        "quoted backend-prefixed key with dotted platform tables",
			toolKeys:    []string{"npm:lodash", "lodash"},
			stale:       []string{"4.17.20"},
			wantChanged: true,
			wantGone:    []string{"4.17.20", "sha256:lodash"},
			wantKept:    []string{"1.22.12", "1.23.8", "20.11.0"},
		},
		{
			name:        "no matching version leaves content untouched",
			toolKeys:    []string{"go"},
			stale:       []string{"9.9.9"},
			wantChanged: false,
		},
		{
			name:        "unknown tool leaves content untouched",
			toolKeys:    []string{"terraform"},
			stale:       []string{"1.22.12"},
			wantChanged: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, changed := PruneLockedVersions([]byte(lock), tt.toolKeys, func(v string) bool {
				return slices.Contains(tt.stale, v)
			})
			if changed != tt.wantChanged {
				t.Fatalf("changed = %v, want %v\n%s", changed, tt.wantChanged, got)
			}
			if !changed {
				if string(got) != lock {
					t.Fatal("content modified despite changed=false")
				}
				return
			}
			for _, s := range tt.wantGone {
				if strings.Contains(string(got), s) {
					t.Errorf("stale marker %q survived:\n%s", s, got)
				}
			}
			for _, s := range tt.wantKept {
				if !strings.Contains(string(got), s) {
					t.Errorf("expected %q to survive:\n%s", s, got)
				}
			}
			if strings.Contains(string(got), "\n\n\n") {
				t.Errorf("pruning left doubled blank lines:\n%s", got)
			}
			// The pruned lockfile must still parse.
			if _, err := ParseLock("mise.lock", got); err != nil {
				t.Errorf("pruned lockfile no longer parses: %v", err)
			}
		})
	}
}

// TestPruneLockedVersionsKeepsTrailingTrivia pins that comments and blank
// lines between a pruned entry and the next one stay with the entry they
// introduce. Deleting them would silently drop annotations belonging to a
// surviving entry, which the function promises to preserve byte-for-byte.
func TestPruneLockedVersionsKeepsTrailingTrivia(t *testing.T) {
	tests := []struct {
		name     string
		lock     string
		want     string
		toolKeys []string
		stale    string
	}{
		{
			name: "comment above the next entry survives",
			lock: `[[tools.go]]
version = "1.22.12"
backend = "core:go"

# node is pinned by the platform team, do not bump
[[tools.node]]
version = "20.11.0"
`,
			want: `# node is pinned by the platform team, do not bump
[[tools.node]]
version = "20.11.0"
`,
			toolKeys: []string{"go"}, stale: "1.22.12",
		},
		{
			name: "comment survives when the pruned entry is in the middle",
			lock: `[[tools.node]]
version = "20.11.0"

[[tools.go]]
version = "1.22.12"

# ripgrep is vendored, keep this entry
[[tools.ripgrep]]
version = "14.1.1"
`,
			want: `[[tools.node]]
version = "20.11.0"

# ripgrep is vendored, keep this entry
[[tools.ripgrep]]
version = "14.1.1"
`,
			toolKeys: []string{"go"}, stale: "1.22.12",
		},
		{
			name: "header comment of the pruned entry goes with it",
			lock: `# go is stale
[[tools.go]]
version = "1.22.12"

[[tools.node]]
version = "20.11.0"
`,
			// The comment above the pruned entry introduces it, so it is not
			// trailing trivia of a previous block and stays put.
			want: `# go is stale
[[tools.node]]
version = "20.11.0"
`,
			toolKeys: []string{"go"}, stale: "1.22.12",
		},
		{
			name: "trailing entry at end of file",
			lock: `[[tools.node]]
version = "20.11.0"

[[tools.go]]
version = "1.22.12"
`,
			want: `[[tools.node]]
version = "20.11.0"
`,
			toolKeys: []string{"go"}, stale: "1.22.12",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, changed := PruneLockedVersions([]byte(tt.lock), tt.toolKeys, func(v string) bool {
				return v == tt.stale
			})
			if !changed {
				t.Fatal("expected the stale entry to be pruned")
			}
			if string(got) != tt.want {
				t.Errorf("prune mismatch:\n--- got ---\n%s\n--- want ---\n%s", got, tt.want)
			}
			if _, err := ParseLock("mise.lock", got); err != nil {
				t.Errorf("pruned lockfile no longer parses: %v", err)
			}
		})
	}
}

func TestSplitKeyPath(t *testing.T) {
	tests := []struct {
		key  string
		want []string
	}{
		{"tools", []string{"tools"}},
		{"tools.go", []string{"tools", "go"}},
		{"tools.go.version", []string{"tools", "go", "version"}},
		{`tools."npm:lodash"`, []string{"tools", "npm:lodash"}},
		{`tools."npm:lodash".version`, []string{"tools", "npm:lodash", "version"}},
		{`tools."aqua:owner/repo"."platforms.linux-x64"`, []string{"tools", "aqua:owner/repo", "platforms.linux-x64"}},
		{`tools . go`, []string{"tools", "go"}},
		{"", nil},
		{"tools..go", nil},
		{`tools."unterminated`, nil},
		// Basic strings are decoded, the way the TOML parser behind Parse
		// decodes them, so an escaped key names the same tool it inventories.
		{`tools."go"`, []string{"tools", "go"}},
		{`tools."g\U0000006f".version`, []string{"tools", "go", "version"}},
		{`tools."g\x6f"`, []string{"tools", "go"}},
		{`tools."npm:lodash".version`, []string{"tools", "npm:lodash", "version"}},
		{`"tools".go`, []string{"tools", "go"}},
		// An escaped quote belongs to the segment; it does not end it.
		{`tools."a\"b".version`, []string{"tools", `a"b`, "version"}},
		{`tools."a\\".version`, []string{"tools", `a\`, "version"}},
		// Literal strings carry no escapes.
		{`tools.'go'`, []string{"tools", `go`}},
		// Escapes TOML does not define, and truncated ones, are refused
		// rather than matched as raw bytes.
		{`tools."a\/b"`, nil},
		{`tools."a\q"`, nil},
		{`tools."a\u00"`, nil},
		{`tools."a\uD800"`, nil},
		{`tools."a\`, nil},
	}
	for _, tt := range tests {
		t.Run(tt.key, func(t *testing.T) {
			if got := SplitKeyPath(tt.key); !slices.Equal(got, tt.want) {
				t.Errorf("SplitKeyPath(%q) = %v, want %v", tt.key, got, tt.want)
			}
		})
	}
}

func TestUnquoteTOMLString(t *testing.T) {
	tests := []struct {
		token string
		want  string
	}{
		{`"1.22.12"`, "1.22.12"},
		{`'1.22.12'`, "1.22.12"},
		{"1.22.12", "1.22.12"},
		{`"1.22.12"`, "1.22.12"},
		{`"a\"b"`, `a"b`},
		{`'ab'`, `ab`},
		{"", ""},
		{`"`, `"`},
		// Unterminated, trailing junk, and undefined escapes leave the token
		// as written so nothing is matched on a half-decoded value.
		{`"unterminated`, `"unterminated`},
		{`"a" trailing`, `"a" trailing`},
		{`"a\/b"`, `"a\/b"`},
		{`'a'b'`, `'a'b'`},
	}
	for _, tt := range tests {
		t.Run(tt.token, func(t *testing.T) {
			if got := UnquoteTOMLString(tt.token); got != tt.want {
				t.Errorf("UnquoteTOMLString(%q) = %q, want %q", tt.token, got, tt.want)
			}
		})
	}
}
