package mise

import (
	"io/fs"
	"maps"
	"slices"
	"testing"
	"testing/fstest"
)

const sampleLock = `
[[tools.node]]
version = "20.11.0"
backend = "core:node"

[tools.node.platforms.linux-x64]
checksum = "sha256:aaa"
size = 23456789
url = "https://nodejs.org/dist/v20.11.0/node-v20.11.0-linux-x64.tar.xz"

[tools.node.platforms.macos-arm64]
checksum = "sha256:bbb"

[[tools.ripgrep]]
version = "14.1.1"
backend = "aqua:BurntSushi/ripgrep"
options = { exe = "rg" }

[tools.ripgrep.platforms.linux-x64]
checksum = "sha256:ccc"
size = 1234567
`

func TestParseLock(t *testing.T) {
	lf, err := ParseLock("mise.lock", []byte(sampleLock))
	if err != nil {
		t.Fatalf("ParseLock: %v", err)
	}

	node := lf.Locked("node", "20.11.0")
	if node == nil {
		t.Fatal("node@20.11.0 not found")
	}
	if node.Backend != "core:node" {
		t.Errorf("node backend = %q", node.Backend)
	}
	sums := node.Checksums()
	if sums["linux-x64"] != "sha256:aaa" || sums["macos-arm64"] != "sha256:bbb" {
		t.Errorf("node checksums = %v", sums)
	}
	if node.Platforms["linux-x64"].Size != 23456789 {
		t.Errorf("node linux-x64 size = %d", node.Platforms["linux-x64"].Size)
	}

	rg := lf.Locked("ripgrep", "14.1.1")
	if rg == nil {
		t.Fatal("ripgrep not found")
	}
	if rg.Options["exe"] != "rg" {
		t.Errorf("ripgrep options = %v", rg.Options)
	}

	if lf.Locked("node", "99.0.0") != nil {
		t.Error("unexpected match for non-existent version")
	}
	if lf.First("ripgrep").Version != "14.1.1" {
		t.Errorf("First(ripgrep) = %v", lf.First("ripgrep"))
	}
	if lf.First("missing") != nil {
		t.Error("First(missing) should be nil")
	}
	if lf.Sole("ripgrep").Version != "14.1.1" {
		t.Errorf("Sole(ripgrep) = %v", lf.Sole("ripgrep"))
	}
}

// realLock mirrors the structure mise actually emits: a backend-qualified,
// quoted tool key and per-platform data under a single quoted dotted key
// ("platforms.<os-arch>") rather than a nested platforms table. Verified
// against temporalio/saas-temporal's committed mise.lock.
const realLock = `# @generated - this file is auto-generated by ` + "`mise lock`" + `
[[tools."aqua:protocolbuffers/protobuf/protoc"]]
version = "33.1"
backend = "aqua:protocolbuffers/protobuf/protoc"

[tools."aqua:protocolbuffers/protobuf/protoc"."platforms.linux-x64"]
checksum = "sha256:f3340e28"
size = 123
url = "https://example/protoc-linux.zip"

[tools."aqua:protocolbuffers/protobuf/protoc"."platforms.macos-arm64"]
checksum = "sha256:db7e66ff"
url = "https://example/protoc-macos.zip"

[[tools.go]]
version = "1.26.3"
backend = "core:go"
`

func TestParseLockRealFormat(t *testing.T) {
	lf, err := ParseLock("mise.lock", []byte(realLock))
	if err != nil {
		t.Fatalf("ParseLock: %v", err)
	}
	protoc := lf.Locked("aqua:protocolbuffers/protobuf/protoc", "33.1")
	if protoc == nil {
		t.Fatal("protoc entry not found under backend-qualified key")
	}
	sums := protoc.Checksums()
	if sums["linux-x64"] != "sha256:f3340e28" || sums["macos-arm64"] != "sha256:db7e66ff" {
		t.Errorf("dotted-key platform checksums not captured: %v", sums)
	}
	if protoc.Platforms["linux-x64"].Size != 123 || protoc.Platforms["linux-x64"].URL == "" {
		t.Errorf("platform size/url not captured: %+v", protoc.Platforms["linux-x64"])
	}
	// A core tool with no platform assets still parses (no checksums).
	if g := lf.Locked("go", "1.26.3"); g == nil || g.Checksums() != nil {
		t.Errorf("go entry = %+v", g)
	}
}

func TestParseLockEmpty(t *testing.T) {
	lf, err := ParseLock("mise.lock", []byte(""))
	if err != nil {
		t.Fatalf("ParseLock empty: %v", err)
	}
	if len(lf.Tools) != 0 {
		t.Errorf("expected no tools, got %d", len(lf.Tools))
	}
	if lf.Locked("x", "1") != nil || lf.First("x") != nil || lf.Sole("x") != nil {
		t.Error("lookups on empty lock should be nil")
	}
}

func TestLockfileLookupAmbiguousFuzzyVersion(t *testing.T) {
	const data = `
[[tools.python]]
version = "3.11.9"

[[tools.python]]
version = "3.12.3"
`
	lf, err := ParseLock("mise.lock", []byte(data))
	if err != nil {
		t.Fatalf("ParseLock: %v", err)
	}

	if got := lf.Lookup(ToolSpec{Name: "python", Key: "python"}, "3.11.9", nil); got == nil || got.Version != "3.11.9" {
		t.Fatalf("exact lookup = %+v, want 3.11.9", got)
	}
	if got := lf.Lookup(ToolSpec{Name: "python", Key: "python"}, "3", nil); got != nil {
		t.Fatalf("ambiguous fuzzy lookup = %+v, want nil", got)
	}
	if got := lf.Sole("python"); got != nil {
		t.Fatalf("Sole(python) = %+v, want nil for multiple entries", got)
	}
}

// TestLockfileLookupContestedName pins that the sole-entry fallback needs an
// uncontested claim, the literal key included. The fallback is a guess: it
// hands a declaration an entry whose version it never asked for, which is only
// defensible when no other declaration could have put that entry there. Two
// conf.d fragments sharing a lockfile can declare the same key, and lending one
// fragment the other's entry reports a version that fragment does not declare,
// which after a fix reads as the vulnerable version coming back.
//
// An exact version match stays available for the literal key: an entry keyed by
// exactly what a declaration spells, at exactly the version it spells, is that
// declaration's however many others share the name.
func TestLockfileLookupContestedName(t *testing.T) {
	const data = `
[[tools.go]]
version = "1.23.4"

[[tools."npm:foo"]]
version = "1.0.0"
`
	lf, err := ParseLock("mise.lock", []byte(data))
	if err != nil {
		t.Fatalf("ParseLock: %v", err)
	}

	tests := []struct {
		name    string
		spec    ToolSpec
		request string
		claims  map[string]int
		want    string // "" means no entry may be borrowed
	}{
		{
			name:    "sole entry serves an uncontested literal key",
			spec:    ToolSpec{Name: "go", Key: "go"},
			request: "1.22",
			claims:  map[string]int{"go": 1},
			want:    "1.23.4",
		},
		{
			name:    "sole entry is refused for a contested literal key",
			spec:    ToolSpec{Name: "go", Key: "go"},
			request: "1.22",
			claims:  map[string]int{"go": 2},
			want:    "",
		},
		{
			name:    "exact match survives a contested literal key",
			spec:    ToolSpec{Name: "go", Key: "go"},
			request: "1.23.4",
			claims:  map[string]int{"go": 2},
			want:    "1.23.4",
		},
		{
			name:    "sole entry is refused for a contested short name",
			spec:    ToolSpec{Name: "foo", Key: "ubi:foo"},
			request: "1",
			claims:  map[string]int{"foo": 2, "npm:foo": 1, "ubi:foo": 1},
			want:    "",
		},
		{
			name:    "no claims recorded leaves the fallback open",
			spec:    ToolSpec{Name: "go", Key: "go"},
			request: "1.22",
			claims:  nil,
			want:    "1.23.4",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := lf.Lookup(tt.spec, tt.request, tt.claims)
			switch {
			case tt.want == "":
				if got != nil {
					t.Fatalf("Lookup = %q, want no entry", got.Version)
				}
			case got == nil:
				t.Fatalf("Lookup = nil, want %q", tt.want)
			case got.Version != tt.want:
				t.Fatalf("Lookup = %q, want %q", got.Version, tt.want)
			}
		})
	}
}

// TestConfigsSharingLock pins which configs mise merges into one lockfile.
// mise 2026.7.3 reports ".config/mise/mise.lock" as the lock target for a tool
// declared only in ".config/mise/conf.d/b.toml", so a mise directory's
// config.toml and every drop-in beside it share one file, while an
// environment-specific config next to them locks somewhere else.
func TestConfigsSharingLock(t *testing.T) {
	const decl = "[tools]\ngo = \"1.22.12\"\n"
	files := fstest.MapFS{
		".config/mise/config.toml":            {Data: []byte(decl)},
		".config/mise/config.production.toml": {Data: []byte(decl)},
		".config/mise/conf.d/a.toml":          {Data: []byte(decl)},
		".config/mise/conf.d/b.toml":          {Data: []byte(decl)},
		".config/mise/notes.md":               {Data: []byte("not a config")},
		"repo/mise.toml":                      {Data: []byte(decl)},
		"repo/.mise.toml":                     {Data: []byte(decl)},
		"repo/mise.staging.toml":              {Data: []byte(decl)},
		"repo/pyproject.toml":                 {Data: []byte("[project]\n")},
		"repo/.tool-versions":                 {Data: []byte("golang 1.22.12\n")},
	}
	tests := []struct {
		name       string
		configPath string
		want       []string
	}{
		{
			name:       "a drop-in shares with its siblings and the directory config",
			configPath: ".config/mise/conf.d/a.toml",
			want: []string{
				".config/mise/conf.d/a.toml",
				".config/mise/conf.d/b.toml",
				".config/mise/config.toml",
			},
		},
		{
			name:       "the directory config shares with its drop-ins",
			configPath: ".config/mise/config.toml",
			want: []string{
				".config/mise/conf.d/a.toml",
				".config/mise/conf.d/b.toml",
				".config/mise/config.toml",
			},
		},
		{
			// config.production.toml locks to mise.production.lock, so the
			// drop-ins are not its business.
			name:       "an environment config keeps its own lockfile",
			configPath: ".config/mise/config.production.toml",
			want:       []string{".config/mise/config.production.toml"},
		},
		{
			// Both spellings of the flat config name the same mise.lock.
			name:       "the dotted and undotted flat configs share",
			configPath: "repo/mise.toml",
			want:       []string{"repo/.mise.toml", "repo/mise.toml"},
		},
		{
			name:       "a non-TOML config has no lockfile",
			configPath: "repo/.tool-versions",
			want:       nil,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := ConfigsSharingLock(files, tt.configPath)
			if err != nil {
				t.Fatalf("ConfigsSharingLock: %v", err)
			}
			if !slices.Equal(got, tt.want) {
				t.Errorf("ConfigsSharingLock(%q) = %q, want %q", tt.configPath, got, tt.want)
			}
		})
	}
}

// TestLockClaims pins that ownership of a shared lock entry is counted over
// every config sharing the lockfile. Counting only the fragment being read
// makes a name look uncontested when a fragment beside it claims it too, and
// the entry then gets lent to one declaration and pruned while fixing another.
func TestLockClaims(t *testing.T) {
	tests := []struct {
		name    string
		files   fstest.MapFS
		config  string
		want    map[string]int
		wantErr bool
	}{
		{
			name: "claims from a sibling drop-in contest the short name",
			files: fstest.MapFS{
				".config/mise/conf.d/a.toml": {Data: []byte("[tools]\n\"npm:foo\" = \"1.0.0\"\n")},
				".config/mise/conf.d/b.toml": {Data: []byte("[tools]\n\"ubi:foo\" = \"2.0.0\"\n")},
			},
			config: ".config/mise/conf.d/a.toml",
			want:   map[string]int{"npm:foo": 1, "ubi:foo": 1, "foo": 2},
		},
		{
			name: "claims from the directory config contest the short name",
			files: fstest.MapFS{
				".config/mise/config.toml":   {Data: []byte("[tools]\nfoo = \"2.0.0\"\n")},
				".config/mise/conf.d/a.toml": {Data: []byte("[tools]\n\"npm:foo\" = \"1.0.0\"\n")},
			},
			config: ".config/mise/conf.d/a.toml",
			want:   map[string]int{"npm:foo": 1, "foo": 2},
		},
		{
			name: "a lone drop-in owns its short name",
			files: fstest.MapFS{
				".config/mise/conf.d/a.toml": {Data: []byte("[tools]\n\"npm:foo\" = \"1.0.0\"\n")},
			},
			config: ".config/mise/conf.d/a.toml",
			want:   map[string]int{"npm:foo": 1, "foo": 1},
		},
		{
			// A config that will not parse is exactly the one whose
			// declarations might have contested the name, so its absence from
			// the count is not a reason to treat the name as owned.
			name: "an unparsable sharing config is an error",
			files: fstest.MapFS{
				".config/mise/conf.d/a.toml": {Data: []byte("[tools]\n\"npm:foo\" = \"1.0.0\"\n")},
				".config/mise/conf.d/b.toml": {Data: []byte("[tools\nbroken\n")},
			},
			config:  ".config/mise/conf.d/a.toml",
			wantErr: true,
		},
		{
			name:    "no filesystem is an error, not an empty count",
			files:   nil,
			config:  ".config/mise/conf.d/a.toml",
			wantErr: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			var fsys fs.FS
			if tt.files != nil {
				fsys = tt.files
			}
			got, err := LockClaims(fsys, tt.config)
			if tt.wantErr {
				if err == nil {
					t.Fatalf("LockClaims(%q) = %v, want an error", tt.config, got)
				}
				return
			}
			if err != nil {
				t.Fatalf("LockClaims: %v", err)
			}
			if !maps.Equal(got, tt.want) {
				t.Errorf("LockClaims(%q) = %v, want %v", tt.config, got, tt.want)
			}
		})
	}
}
