// Package secrets provides secret detection capabilities.
package secrets

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

// HookType represents the type of git hook.
type HookType string

const (
	HookPreCommit HookType = "pre-commit"
	HookPrePush   HookType = "pre-push"
)

// HookConfig configures hook generation.
type HookConfig struct {
	// HookType is the type of hook to generate.
	HookType HookType

	// FailOnSecrets determines whether the hook should fail if secrets are found.
	// If false, it will only warn.
	FailOnSecrets bool

	// VerifySecrets enables verification of detected secrets.
	VerifySecrets bool

	// Format is the output format for the hook (text, json, sarif).
	Format string

	// ExcludePatterns are file patterns to exclude from scanning.
	ExcludePatterns []string

	// IncludePatterns are file patterns to include (if empty, scans all).
	IncludePatterns []string

	// DeputyPath is the path to the deputy binary.
	// If empty, assumes "deputy" is in PATH.
	DeputyPath string

	// AllowList is a path to an allowlist/baseline file.
	AllowList string

	// ScanStaged only scans staged files (for pre-commit).
	ScanStaged bool

	// Diff mode for pre-push (compare branches).
	DiffMode bool
}

// DefaultHookConfig returns sensible defaults for hook generation.
func DefaultHookConfig(hookType HookType) HookConfig {
	return HookConfig{
		HookType:      hookType,
		FailOnSecrets: true,
		Format:        "text",
		DeputyPath:    "deputy",
		ScanStaged:    hookType == HookPreCommit,
		DiffMode:      hookType == HookPrePush,
	}
}

// preCommitTemplate is the shell script template for pre-commit hooks.
const preCommitTemplate = `#!/bin/bash
# Deputy Pre-Commit Hook - Secret Detection
# Generated by: deputy secrets hook --install
# Documentation: https://github.com/temporalio/deputy

set -e

# Configuration
DEPUTY_PATH="{{.DeputyPath}}"
FAIL_ON_SECRETS={{if .FailOnSecrets}}true{{else}}false{{end}}
FORMAT="{{.Format}}"
{{- if .VerifySecrets}}
VERIFY="--verify"
{{- else}}
VERIFY=""
{{- end}}
{{- if .ExcludePatterns}}
EXCLUDE="--exclude '{{join .ExcludePatterns ","}}'"
{{- else}}
EXCLUDE=""
{{- end}}
{{- if .IncludePatterns}}
INCLUDE="--include '{{join .IncludePatterns ","}}'"
{{- else}}
INCLUDE=""
{{- end}}
{{- if .AllowList}}
ALLOWLIST="--allowlist '{{.AllowList}}'"
{{- else}}
ALLOWLIST=""
{{- end}}

# Check if deputy is available
if ! command -v "$DEPUTY_PATH" &> /dev/null; then
    echo "Warning: deputy not found. Skipping secret scan."
    echo "Install: go install github.com/temporalio/deputy@latest"
    exit 0
fi

# Get staged files
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACMR)

if [ -z "$STAGED_FILES" ]; then
    # No staged files, nothing to scan
    exit 0
fi

echo "Scanning staged files for secrets..."

# Create temp directory for staged content
TEMP_DIR=$(mktemp -d)
trap "rm -rf $TEMP_DIR" EXIT

# Export staged content to temp directory
for FILE in $STAGED_FILES; do
    # Skip binary files and common non-text files
    if file "$FILE" 2>/dev/null | grep -q "binary"; then
        continue
    fi

    # Create directory structure
    mkdir -p "$TEMP_DIR/$(dirname "$FILE")"

    # Export staged version of file
    git show ":$FILE" > "$TEMP_DIR/$FILE" 2>/dev/null || continue
done

# Run deputy secrets scan on temp directory
RESULT=$("$DEPUTY_PATH" secrets "$TEMP_DIR" --format "$FORMAT" $VERIFY $EXCLUDE $INCLUDE $ALLOWLIST 2>&1) || true

# Check for secrets
if echo "$RESULT" | grep -q "Secrets Detected\|secretsFound.*[1-9]"; then
    echo ""
    echo "========================================="
    echo "  SECRETS DETECTED IN STAGED FILES"
    echo "========================================="
    echo ""
    echo "$RESULT"
    echo ""

    if [ "$FAIL_ON_SECRETS" = true ]; then
        echo "Commit blocked. Remove secrets before committing."
        echo ""
        echo "If this is a false positive, you can:"
        echo "  1. Add to allowlist: deputy secrets allowlist add <pattern>"
        echo "  2. Skip this hook: git commit --no-verify"
        echo ""
        exit 1
    else
        echo "Warning: Secrets detected but hook configured to warn only."
    fi
else
    echo "No secrets detected in staged files."
fi

exit 0
`

// prePushTemplate is the shell script template for pre-push hooks.
const prePushTemplate = `#!/bin/bash
# Deputy Pre-Push Hook - Secret Detection
# Generated by: deputy secrets hook --install
# Documentation: https://github.com/temporalio/deputy

set -e

# Configuration
DEPUTY_PATH="{{.DeputyPath}}"
FAIL_ON_SECRETS={{if .FailOnSecrets}}true{{else}}false{{end}}
FORMAT="{{.Format}}"
{{- if .VerifySecrets}}
VERIFY="--verify"
{{- else}}
VERIFY=""
{{- end}}
{{- if .ExcludePatterns}}
EXCLUDE="--exclude '{{join .ExcludePatterns ","}}'"
{{- else}}
EXCLUDE=""
{{- end}}
{{- if .AllowList}}
ALLOWLIST="--allowlist '{{.AllowList}}'"
{{- else}}
ALLOWLIST=""
{{- end}}

# Check if deputy is available
if ! command -v "$DEPUTY_PATH" &> /dev/null; then
    echo "Warning: deputy not found. Skipping secret scan."
    echo "Install: go install github.com/temporalio/deputy@latest"
    exit 0
fi

# Read stdin for push info (format: local_ref local_sha remote_ref remote_sha)
while read LOCAL_REF LOCAL_SHA REMOTE_REF REMOTE_SHA; do
    if [ "$LOCAL_SHA" = "0000000000000000000000000000000000000000" ]; then
        # Branch is being deleted, nothing to check
        continue
    fi

    if [ "$REMOTE_SHA" = "0000000000000000000000000000000000000000" ]; then
        # New branch, check all commits
        RANGE="$LOCAL_SHA"
    else
        # Existing branch, check new commits
        RANGE="$REMOTE_SHA..$LOCAL_SHA"
    fi

    echo "Scanning commits for secrets: $RANGE"

    # Use deputy diff mode to scan changes
    if [ "$REMOTE_SHA" != "0000000000000000000000000000000000000000" ]; then
        RESULT=$("$DEPUTY_PATH" secrets --diff "$REMOTE_SHA" "$LOCAL_SHA" --format "$FORMAT" $EXCLUDE $ALLOWLIST 2>&1) || true
    else
        # For new branches, scan the full commit range
        RESULT=$("$DEPUTY_PATH" secrets --history --branch "$LOCAL_REF" --format "$FORMAT" $EXCLUDE $ALLOWLIST 2>&1) || true
    fi

    # Check for secrets
    if echo "$RESULT" | grep -q "Secrets Detected\|New Secrets Detected\|secretsFound.*[1-9]\|newSecrets.*[1-9]"; then
        echo ""
        echo "========================================="
        echo "  SECRETS DETECTED IN PUSH"
        echo "========================================="
        echo ""
        echo "$RESULT"
        echo ""

        if [ "$FAIL_ON_SECRETS" = true ]; then
            echo "Push blocked. Remove secrets before pushing."
            echo ""
            echo "To fix:"
            echo "  1. Remove the secret from your code"
            echo "  2. Rotate the exposed credential immediately"
            echo "  3. Amend or rebase to remove from history"
            echo ""
            echo "If this is a false positive:"
            echo "  git push --no-verify"
            echo ""
            exit 1
        else
            echo "Warning: Secrets detected but hook configured to warn only."
        fi
    else
        echo "No new secrets detected."
    fi
done

exit 0
`

// GenerateHook generates a git hook script.
func GenerateHook(w io.Writer, config HookConfig) error {
	funcMap := template.FuncMap{
		"join": strings.Join,
	}

	var tmplStr string
	switch config.HookType {
	case HookPreCommit:
		tmplStr = preCommitTemplate
	case HookPrePush:
		tmplStr = prePushTemplate
	default:
		return fmt.Errorf("unsupported hook type: %s", config.HookType)
	}

	tmpl, err := template.New("hook").Funcs(funcMap).Parse(tmplStr)
	if err != nil {
		return fmt.Errorf("parsing hook template: %w", err)
	}

	return tmpl.Execute(w, config)
}

// InstallHook installs a git hook in the specified repository.
func InstallHook(repoPath string, config HookConfig) error {
	// Find .git directory
	gitDir := filepath.Join(repoPath, ".git")
	if info, err := os.Stat(gitDir); err != nil || !info.IsDir() {
		return fmt.Errorf("not a git repository: %s", repoPath)
	}

	// Create hooks directory if needed
	hooksDir := filepath.Join(gitDir, "hooks")
	if err := os.MkdirAll(hooksDir, 0755); err != nil {
		return fmt.Errorf("creating hooks directory: %w", err)
	}

	// Generate hook path
	hookPath := filepath.Join(hooksDir, string(config.HookType))

	// Check if hook already exists
	if _, err := os.Stat(hookPath); err == nil {
		// Backup existing hook
		backupPath := hookPath + ".backup"
		if err := os.Rename(hookPath, backupPath); err != nil {
			return fmt.Errorf("backing up existing hook: %w", err)
		}
	}

	// Create hook file
	f, err := os.OpenFile(hookPath, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0755)
	if err != nil {
		return fmt.Errorf("creating hook file: %w", err)
	}
	defer f.Close()

	// Generate hook content
	if err := GenerateHook(f, config); err != nil {
		return fmt.Errorf("generating hook: %w", err)
	}

	return nil
}

// UninstallHook removes a git hook from the specified repository.
func UninstallHook(repoPath string, hookType HookType) error {
	hookPath := filepath.Join(repoPath, ".git", "hooks", string(hookType))

	// Check if hook exists
	if _, err := os.Stat(hookPath); os.IsNotExist(err) {
		return fmt.Errorf("hook not installed: %s", hookType)
	}

	// Remove hook
	if err := os.Remove(hookPath); err != nil {
		return fmt.Errorf("removing hook: %w", err)
	}

	// Restore backup if it exists
	backupPath := hookPath + ".backup"
	if _, err := os.Stat(backupPath); err == nil {
		if err := os.Rename(backupPath, hookPath); err != nil {
			return fmt.Errorf("restoring backup hook: %w", err)
		}
	}

	return nil
}

// ListInstalledHooks returns which deputy hooks are installed in the repository.
func ListInstalledHooks(repoPath string) ([]HookType, error) {
	hooksDir := filepath.Join(repoPath, ".git", "hooks")

	var installed []HookType
	for _, hookType := range []HookType{HookPreCommit, HookPrePush} {
		hookPath := filepath.Join(hooksDir, string(hookType))
		if content, err := os.ReadFile(hookPath); err == nil {
			// Check if it's a deputy hook
			if strings.Contains(string(content), "Deputy") {
				installed = append(installed, hookType)
			}
		}
	}

	return installed, nil
}

// HookStatus represents the status of a hook.
type HookStatus struct {
	Type      HookType
	Installed bool
	IsDeputy  bool // True if it's a deputy-generated hook
	HasBackup bool // True if there's a backup of previous hook
}

// GetHookStatus returns the status of hooks in the repository.
func GetHookStatus(repoPath string) ([]HookStatus, error) {
	hooksDir := filepath.Join(repoPath, ".git", "hooks")

	var statuses []HookStatus
	for _, hookType := range []HookType{HookPreCommit, HookPrePush} {
		status := HookStatus{Type: hookType}

		hookPath := filepath.Join(hooksDir, string(hookType))
		if content, err := os.ReadFile(hookPath); err == nil {
			status.Installed = true
			status.IsDeputy = strings.Contains(string(content), "Deputy")
		}

		backupPath := hookPath + ".backup"
		if _, err := os.Stat(backupPath); err == nil {
			status.HasBackup = true
		}

		statuses = append(statuses, status)
	}

	return statuses, nil
}
