package surface

import (
	"bufio"
	"fmt"
	"os"
	"slices"
	"strings"
)

// BaselinePath is the committed record of packages under internal/ that no
// other package imports, relative to the repository root. It is generated by
// command internal/surface/cmd with -baseline and pinned by a test, so adding a
// package nothing reaches fails CI instead of passing unnoticed.
const BaselinePath = "internal/surface/testdata/unreachable.txt"

// baselineHeader explains the file to whoever opens it after a failing test.
const baselineHeader = `# Packages under internal/ that no other package imports, as measured by
# go/types. Each entry is code only its own tests reach, which is why
# unused-symbol analysis does not flag it.
#
# This file is generated. Regenerate it with:
#
#	go run ./internal/surface/cmd -baseline
#
# Entries should only ever be removed. A new entry means a package was added
# or orphaned with nothing importing it; wire it up or delete it rather than
# recording it here.
`

// WriteBaseline writes the report's unreachable packages to path.
func WriteBaseline(path string, r *Report) error {
	var b strings.Builder
	b.WriteString(baselineHeader)
	for _, f := range r.Packages {
		fmt.Fprintf(&b, "%s\n", f.Dir)
	}
	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		return fmt.Errorf("write baseline %s: %w", path, err)
	}
	return nil
}

// ReadBaseline reads the recorded package directories from path, ignoring
// comments and blank lines.
func ReadBaseline(path string) ([]string, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, fmt.Errorf("read baseline %s: %w", path, err)
	}
	defer f.Close()

	var out []string
	scan := bufio.NewScanner(f)
	for scan.Scan() {
		line := strings.TrimSpace(scan.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		out = append(out, line)
	}
	if err := scan.Err(); err != nil {
		return nil, fmt.Errorf("read baseline %s: %w", path, err)
	}
	slices.Sort(out)
	return out, nil
}

// UnreachableDirs returns the report's unreachable package directories, sorted,
// for comparison against a baseline.
func (r *Report) UnreachableDirs() []string {
	out := make([]string, 0, len(r.Packages))
	for _, f := range r.Packages {
		out = append(out, f.Dir)
	}
	slices.Sort(out)
	return out
}
