package surface

import (
	"bufio"
	"fmt"
	"os"
	"slices"
	"strings"
)

// BaselinePath is the committed record of packages under internal/ that no
// other package imports, relative to the repository root. It is generated by
// command internal/surface/cmd with -baseline and pinned by a test, so adding a
// package nothing reaches fails CI instead of passing unnoticed.
const BaselinePath = "internal/surface/testdata/unreachable.txt"

// baselineRemedy is what to do about a package nothing imports. Recording it is
// not on the list, and stating that once is what keeps the file a ratchet: an
// entry added for a newly orphaned package makes the check pass without the
// package being wired up or deleted, which is the one edit that turns the
// baseline from a shrinking record into a place to park dead code.
const baselineRemedy = "wire it up or delete it"

// baselineCommand regenerates the file. It belongs only in the message about an
// entry that is no longer unreachable, because shrinking the baseline is the
// only edit the ratchet accepts; offering it for a new orphan offers the remedy
// [baselineRemedy] rules out.
const baselineCommand = "go run ./internal/surface/cmd -baseline"

// baselineHeader explains the file to whoever opens it after a failing test.
var baselineHeader = fmt.Sprintf(`# Packages under internal/ that no other package imports, as measured by
# go/types. Each entry is code only its own tests reach, which is why
# unused-symbol analysis does not flag it.
#
# This file is generated, and regenerating it is how an entry leaves:
#
#	%s
#
# Entries should only ever be removed. A new entry means a package was added
# or orphaned with nothing importing it; %s
# rather than recording it here.
`, baselineCommand, baselineRemedy)

// WriteBaseline writes the report's unreachable packages to path.
func WriteBaseline(path string, r *Report) error {
	var b strings.Builder
	b.WriteString(baselineHeader)
	for _, f := range r.Packages {
		fmt.Fprintf(&b, "%s\n", f.Dir)
	}
	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		return fmt.Errorf("write baseline %s: %w", path, err)
	}
	return nil
}

// ReadBaseline reads the recorded package directories from path, ignoring
// comments and blank lines.
func ReadBaseline(path string) ([]string, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, fmt.Errorf("read baseline %s: %w", path, err)
	}
	defer f.Close()

	var out []string
	scan := bufio.NewScanner(f)
	for scan.Scan() {
		line := strings.TrimSpace(scan.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		out = append(out, line)
	}
	if err := scan.Err(); err != nil {
		return nil, fmt.Errorf("read baseline %s: %w", path, err)
	}
	slices.Sort(out)
	return out, nil
}

// UnreachableDirs returns the report's unreachable package directories, sorted,
// for comparison against a baseline.
func (r *Report) UnreachableDirs() []string {
	out := make([]string, 0, len(r.Packages))
	for _, f := range r.Packages {
		out = append(out, f.Dir)
	}
	slices.Sort(out)
	return out
}
